/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.AcsCliente;
import bean.AcsFuncionario;
import bean.AcsVendas;
import bean.AcsVendasProduto;
import dao.DaoCliente;
import dao.DaoFuncionarios;
import dao.DaoProduto;
import dao.DaoVendas;
import dao.DaoVendasProduto;


import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;
import view.VendaControle;
import view.VendasProdutoControle;


/**
 *
 * @author u09564875137
 */
public class AcsTelaVenda extends javax.swing.JDialog {

     MaskFormatter mascaraData;
     

    private boolean incluindo;
    DaoVendas daoVendas;
    AcsVendas acsVendas;
    VendaControle vendaControle;
    AcsVendasProduto acsVendasProduto;
    DaoVendasProduto daoVendasProduto;
    VendasProdutoControle vendasProdutoControle;
    AcsCliente acsCliente;
    AcsTelaVendaPesquisar acsTelaVendaPesquisar;
    AcsTelaVendaProduto acsTelaVendaProduto;
    
    
    /**
     * Creates new form AcsVendas
     */
    public AcsTelaVenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Tela de Vendas");
        Util.habilitar(false, acs_jTxtcodigo, acs_jFmtdata, acs_jCbocliente, acs_jCbofuncionario, acs_jFmtvalor, acs_jBtnalterar1, acs_jBtnexcluir1,acs_jBtnincluir1, acs_jBtnconfirmar, acs_jBtncancelar );
        setLocationRelativeTo(null);
        daoVendas = new DaoVendas();
       
       
       
       
        
        DaoCliente daoCliente = new DaoCliente();
        List listaCli = daoCliente.listAll(); 
        for (int i = 0; i < listaCli.size(); i++) {
        acs_jCbocliente.addItem((AcsCliente) listaCli.get(i));
        }
        DaoFuncionarios daoFuncionario = new DaoFuncionarios();
        List listaFun = daoFuncionario.listAll(); 
        for (int a = 0; a < listaCli.size(); a++) {
        acs_jCbofuncionario.addItem((AcsFuncionario) listaFun.get(a));
        }
        
         vendasProdutoControle = new VendasProdutoControle();
         List lista = new ArrayList();
        vendasProdutoControle.setList(lista);
        jTable1.setModel(vendasProdutoControle);
        try {
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(AcsTelaVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        acs_jFmtdata.setFormatterFactory(new DefaultFormatterFactory(mascaraData));

    }


     public AcsVendas viewBean() {
       AcsVendas acsvendas = new AcsVendas();
       int id = Util.strInt(acs_jTxtcodigo.getText());
       acsvendas.setAcsIdvendas(id);
         try {
             acsvendas.setAcsHorapedido(Util.strDate(acs_jFmtdata.getText()));
         } catch (ParseException ex) {
             Logger.getLogger(AcsTelaVenda.class.getName()).log(Level.SEVERE, null, ex);
         }
       acsvendas.setAcsCliente((AcsCliente) acs_jCbocliente.getSelectedItem());
       acsvendas.setAcsFuncionario((AcsFuncionario)acs_jCbofuncionario.getSelectedItem());
       double total = Util.strDouble(acs_jFmtvalor.getText());
       acsvendas.setAcsValor(total);
        return acsvendas;
    }
     

    public void beanView(AcsVendas vendas) {
        acsVendas = vendas;
        acs_jTxtcodigo.setText(String.valueOf(vendas.getAcsIdvendas()));
        acs_jFmtdata.setText(Util.dateStr(vendas.getAcsHorapedido()));
        acs_jCbocliente.setSelectedItem(vendas.getAcsCliente());
        acs_jCbofuncionario.setSelectedItem(vendas.getAcsFuncionario());
        acs_jFmtvalor.setText(String.valueOf(vendas.getAcsValor()));

       daoVendasProduto = new DaoVendasProduto();
       List listaProd = (List) daoVendasProduto.listProduto(acsVendas);
       vendasProdutoControle.setList(listaProd);
    }

    
    public int getSelectedRowProd() {
        return jTable1.getSelectedRow();
    
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        acs_jBtnexcluir1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        acs_jTxtcodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        acs_jCbocliente = new javax.swing.JComboBox<AcsCliente>();
        jLabel3 = new javax.swing.JLabel();
        acs_jCbofuncionario = new javax.swing.JComboBox<AcsFuncionario>();
        jLabel4 = new javax.swing.JLabel();
        acs_jFmtvalor = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        acs_jFmtdata = new javax.swing.JFormattedTextField();
        acs_jBtnalterar1 = new javax.swing.JButton();
        acs_jBtnincluir1 = new javax.swing.JButton();
        acs_jBtnincluir = new javax.swing.JButton();
        acs_jBtnalterar = new javax.swing.JButton();
        acs_jBtnconfirmar = new javax.swing.JButton();
        acs_jBtnexcluir = new javax.swing.JButton();
        acs_jBtnpesquisar = new javax.swing.JButton();
        acs_jBtncancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jButton6.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        acs_jBtnexcluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-lixo-20.png"))); // NOI18N
        acs_jBtnexcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnexcluir1ActionPerformed(evt);
            }
        });

        jLabel1.setText("CODIGO");

        jLabel2.setText("CLIENTE");

        jLabel3.setText("FUNCIONARIO");

        jLabel4.setText("VALOR");

        acs_jFmtvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jFmtvalorActionPerformed(evt);
            }
        });

        jLabel5.setText("DATA");

        acs_jBtnalterar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-editar-20.png"))); // NOI18N
        acs_jBtnalterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnalterar1ActionPerformed(evt);
            }
        });

        acs_jBtnincluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-mais-20.png"))); // NOI18N
        acs_jBtnincluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnincluir1ActionPerformed(evt);
            }
        });

        acs_jBtnincluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-mais-20.png"))); // NOI18N
        acs_jBtnincluir.setText("INCLUIR");
        acs_jBtnincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnincluirActionPerformed(evt);
            }
        });

        acs_jBtnalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-editar-20.png"))); // NOI18N
        acs_jBtnalterar.setText("ALTERAR");
        acs_jBtnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnalterarActionPerformed(evt);
            }
        });

        acs_jBtnconfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-selecionado-20.png"))); // NOI18N
        acs_jBtnconfirmar.setText("CONFIRMAR");
        acs_jBtnconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnconfirmarActionPerformed(evt);
            }
        });

        acs_jBtnexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-lixo-20.png"))); // NOI18N
        acs_jBtnexcluir.setText("EXCLUIR");
        acs_jBtnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnexcluirActionPerformed(evt);
            }
        });

        acs_jBtnpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pesquisar-20.png"))); // NOI18N
        acs_jBtnpesquisar.setText("PESQUISAR");
        acs_jBtnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnpesquisarActionPerformed(evt);
            }
        });

        acs_jBtncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-excluir-20.png"))); // NOI18N
        acs_jBtncancelar.setText("CANCELAR");
        acs_jBtncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtncancelarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-finalizar-pedido-64.png"))); // NOI18N
        jLabel6.setText("VENDAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(acs_jBtnalterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(acs_jBtnincluir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(160, 160, 160)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(acs_jBtnconfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(acs_jBtncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(acs_jBtnexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(acs_jBtnpesquisar))
                                .addGap(13, 13, 13)))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acs_jBtnalterar1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(acs_jBtnincluir1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(acs_jBtnexcluir1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(acs_jTxtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(acs_jCbocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acs_jCbofuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acs_jFmtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acs_jFmtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jTxtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acs_jCbocliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acs_jCbofuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acs_jFmtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acs_jFmtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acs_jBtnincluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(acs_jBtnalterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acs_jBtnexcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jBtnincluir)
                    .addComponent(acs_jBtnconfirmar)
                    .addComponent(acs_jBtnpesquisar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jBtnalterar)
                    .addComponent(acs_jBtnexcluir)
                    .addComponent(acs_jBtncancelar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acs_jBtnalterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnalterar1ActionPerformed
        acsTelaVendaProduto = new AcsTelaVendaProduto(null, true);
        acsTelaVendaProduto.setTitle("Alteração de produtos");
        acsTelaVendaProduto.setTelaAnterior(this);
        
        int linSel = jTable1.getSelectedRow();
        acsVendasProduto = (AcsVendasProduto) vendasProdutoControle.getBean(linSel);
        acsTelaVendaProduto.beanView(acsVendasProduto);
        acsTelaVendaProduto.setVisible(true);
        
    }//GEN-LAST:event_acs_jBtnalterar1ActionPerformed

    private void acs_jBtnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnpesquisarActionPerformed
        Util.limparCampos(jTable1, acs_jTxtcodigo, acs_jFmtvalor, acs_jFmtdata, acs_jCbocliente, acs_jCbofuncionario);
        
        AcsTelaVendaPesquisar acsTelaVendaPesquisar = new AcsTelaVendaPesquisar(null, true);
        acsTelaVendaPesquisar.setTelaAnterior(this);
        acsTelaVendaPesquisar.setVisible(true);
        
    }//GEN-LAST:event_acs_jBtnpesquisarActionPerformed

    private void acs_jBtnincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnincluirActionPerformed
        Util.habilitar(true, acs_jTxtcodigo, acs_jFmtdata, acs_jCbocliente, acs_jCbofuncionario, acs_jFmtvalor, acs_jBtnalterar1, acs_jBtnexcluir1,acs_jBtnincluir1, acs_jBtnconfirmar, acs_jBtncancelar);
        Util.habilitar(false, acs_jBtnexcluir, acs_jBtnalterar, acs_jBtnincluir, acs_jBtnpesquisar);

      
        vendasProdutoControle.setList(new ArrayList());
        acs_jTxtcodigo.grabFocus();
        incluindo = true;
        acsVendas = new AcsVendas();
         Util.limparCampos(acs_jTxtcodigo, acs_jFmtdata, acs_jCbocliente, acs_jCbofuncionario, acs_jFmtvalor);
    }//GEN-LAST:event_acs_jBtnincluirActionPerformed

    private void acs_jBtnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnalterarActionPerformed
Util.habilitar(false, acs_jBtnexcluir, acs_jBtnincluir, acs_jBtnalterar, acs_jBtnpesquisar);

        if (acsVendas != null) {
            
           daoVendas = new DaoVendas();
                AcsVendasProduto acsVendasProduto;
                for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                    acsVendasProduto = vendasProdutoControle.getBean(linha);
                    daoVendas.delete(acsVendasProduto);}
                
                
            Util.habilitar(true, acs_jTxtcodigo, acs_jFmtdata, acs_jCbocliente, acs_jCbofuncionario, acs_jFmtvalor, acs_jBtnalterar1, acs_jBtnexcluir1,acs_jBtnincluir1, acs_jBtnconfirmar, acs_jBtncancelar);
            Util.habilitar(false, acs_jBtnexcluir, acs_jBtnalterar, acs_jBtnincluir, acs_jBtnpesquisar);

        } else {
            Util.mensagem("Deve ser realizada uma pesquisa antes");
        }
        incluindo = false;
    
    }//GEN-LAST:event_acs_jBtnalterarActionPerformed

    private void acs_jBtnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnexcluirActionPerformed
        if (acsVendas != null) {
            if (Util.perguntar("Deseja excluir o pedido ?") == true) {
                AcsVendasProduto acsVendasProduto;
                for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                    acsVendasProduto = vendasProdutoControle.getBean(linha);
                    daoVendas.delete(acsVendasProduto);
                }
                daoVendas.delete(acsVendas);
            }
        } else {
            Util.mensagem("Primeiramente realize uma pesquisa");
        }
        vendasProdutoControle.setList(new ArrayList());
        Util.limparCampos(acs_jTxtcodigo, acs_jFmtdata, acs_jCbocliente, acs_jCbofuncionario, acs_jFmtvalor);
        acsVendas = null;
    }//GEN-LAST:event_acs_jBtnexcluirActionPerformed

    private void acs_jBtnconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnconfirmarActionPerformed
         acsVendas = viewBean();
        if (incluindo == true) {
            daoVendas.insert(acsVendas);
             daoVendasProduto = new DaoVendasProduto();
            
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                acsVendasProduto = vendasProdutoControle.getBean(linha);
                acsVendasProduto.setAcsVendas(acsVendas);
                  daoVendasProduto.insert(acsVendasProduto);
            }
        } else {
            daoVendas.update(acsVendas);
            daoVendasProduto = new DaoVendasProduto();
            
        
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                acsVendasProduto = vendasProdutoControle.getBean(linha);
                acsVendasProduto.setAcsVendas(acsVendas);
                daoVendasProduto.insert(acsVendasProduto);
               
            }
            
           
        }
        Util.limparCampos(acs_jTxtcodigo, acs_jFmtdata, acs_jCbocliente, acs_jCbofuncionario, acs_jFmtvalor);
        vendasProdutoControle.setList(new ArrayList());

        acsVendas = null;
        
        Util.habilitar(false, acs_jTxtcodigo, acs_jFmtdata, acs_jCbocliente, acs_jCbofuncionario, acs_jFmtvalor, acs_jBtnalterar1, acs_jBtnexcluir1,acs_jBtnincluir1, acs_jBtnconfirmar, acs_jBtncancelar);
        Util.habilitar(true, acs_jBtnexcluir, acs_jBtnalterar, acs_jBtnincluir, acs_jBtnpesquisar);
  
    }//GEN-LAST:event_acs_jBtnconfirmarActionPerformed

    private void acs_jBtncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtncancelarActionPerformed
Util.limparCampos(acs_jTxtcodigo, acs_jFmtdata, acs_jCbocliente, acs_jCbofuncionario, acs_jFmtvalor);
        vendasProdutoControle.setList(new ArrayList());
        acsVendas = null;
        Util.habilitar(false, acs_jTxtcodigo, acs_jFmtdata, acs_jCbocliente, acs_jCbofuncionario, acs_jFmtvalor, acs_jBtnalterar1, acs_jBtnexcluir1,acs_jBtnincluir1, acs_jBtnconfirmar, acs_jBtncancelar);
        Util.habilitar(true, acs_jBtnexcluir, acs_jBtnalterar, acs_jBtnincluir, acs_jBtnpesquisar);

    }//GEN-LAST:event_acs_jBtncancelarActionPerformed

    private void acs_jBtnincluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnincluir1ActionPerformed
        acsTelaVendaProduto = new AcsTelaVendaProduto(null, true);
        acsTelaVendaProduto.setTitle("inclusão de produtos");
        acsTelaVendaProduto.setTelaAnterior(this);
        acsTelaVendaProduto.setVisible(true);
    }//GEN-LAST:event_acs_jBtnincluir1ActionPerformed

    private void acs_jBtnexcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnexcluir1ActionPerformed
       int linha = jTable1.getSelectedRow();
        if (linha == -1) {
            Util.mensagem("Nenhuma linha selecionada");
        } else {
            if (Util.perguntar("Confirma exclusão do produto?") == true) {
                vendasProdutoControle.removeBean(linha);
            }
        }
    }//GEN-LAST:event_acs_jBtnexcluir1ActionPerformed

    private void acs_jFmtvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jFmtvalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jFmtvalorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcsTelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcsTelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcsTelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcsTelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AcsTelaVenda dialog = new AcsTelaVenda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acs_jBtnalterar;
    private javax.swing.JButton acs_jBtnalterar1;
    private javax.swing.JButton acs_jBtncancelar;
    private javax.swing.JButton acs_jBtnconfirmar;
    private javax.swing.JButton acs_jBtnexcluir;
    private javax.swing.JButton acs_jBtnexcluir1;
    private javax.swing.JButton acs_jBtnincluir;
    private javax.swing.JButton acs_jBtnincluir1;
    private javax.swing.JButton acs_jBtnpesquisar;
    private javax.swing.JComboBox<AcsCliente> acs_jCbocliente;
    private javax.swing.JComboBox<AcsFuncionario> acs_jCbofuncionario;
    private javax.swing.JFormattedTextField acs_jFmtdata;
    private javax.swing.JFormattedTextField acs_jFmtvalor;
    private javax.swing.JTextField acs_jTxtcodigo;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
