/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.AcsUsuario;
import dao.DaoUsuario;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;


/**
 *
 * @author ENTERPRISE
 */
public class AcsTelaUsuario extends javax.swing.JDialog {

    private boolean incluindo;
    MaskFormatter mascaraCPF, mascaraData;
    public AcsUsuario usuarios;
    public DaoUsuario DaoUsuario;

    public AcsTelaUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        DaoUsuario = new DaoUsuario();

        Util.habilitar(false, acs_jTxtcodigo, acs_jTxtnome, acs_jTxtapelido, acs_jFmtcpf, acs_jFmtdata,
                acs_jPwfsenha, acs_jCbonivel, acs_jChbativo, acs_jBtncancelar, acs_jBtnconfirmar);
            Util.habilitar(true, acs_jBtnincluir, acs_jBtnalterar, acs_jBtnexcluir, acs_jBtnpesquisar);

        setTitle("Cadastro de usuários");
        setLocationRelativeTo(null);
        try {
            mascaraCPF = new MaskFormatter("###.###.###-##");
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(AcsTelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        acs_jFmtcpf.setFormatterFactory(new DefaultFormatterFactory(mascaraCPF));
        acs_jFmtdata.setFormatterFactory(new DefaultFormatterFactory(mascaraData));

    }

    public AcsUsuario viewBean() {
        AcsUsuario usuarios = new AcsUsuario();
        usuarios.setAcsIdusuario(Util.strInt(acs_jTxtcodigo.getText()));
        usuarios.setAcsNome(acs_jTxtnome.getText());
        usuarios.setAcsApelido(acs_jTxtapelido.getText());
        usuarios.setAcsCpf(acs_jFmtcpf.getText());
        usuarios.setAcsDataNasc(acs_jFmtdata.getText());
        usuarios.setAcsSenha(acs_jPwfsenha.getText());
        usuarios.setAcsNivel(acs_jCbonivel.getSelectedIndex());
        usuarios.setAcsAtivo( acs_jChbativo.isSelected() == true ? "S" : "N");
        
       if (acs_jChbativo.isSelected() == true) {
           usuarios.setAcsAtivo("S");
        } else {
            usuarios.setAcsAtivo("N");
       }
        return usuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acs_jTxtcodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        acs_jTxtnome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        acs_jTxtapelido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        acs_jFmtcpf = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        acs_jFmtdata = new javax.swing.JFormattedTextField();
        acs_jChbativo = new javax.swing.JCheckBox();
        acs_jCbonivel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        acs_jPwfsenha = new javax.swing.JPasswordField();
        acs_jBtnincluir = new javax.swing.JButton();
        acs_jBtnalterar = new javax.swing.JButton();
        acs_jBtnconfirmar = new javax.swing.JButton();
        acs_jBtnpesquisar = new javax.swing.JButton();
        acs_jBtnexcluir = new javax.swing.JButton();
        acs_jBtncancelar = new javax.swing.JButton();

        jButton6.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Usuario");

        jLabel2.setText("CODIGO");

        acs_jTxtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtcodigoActionPerformed(evt);
            }
        });

        jLabel3.setText("NOME");

        acs_jTxtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtnomeActionPerformed(evt);
            }
        });

        jLabel4.setText("APELIDO");

        jLabel5.setText("CPF");

        acs_jFmtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jFmtcpfActionPerformed(evt);
            }
        });

        jLabel7.setText("DATA NASCMENTO");

        acs_jChbativo.setText("ATIVO");
        acs_jChbativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jChbativoActionPerformed(evt);
            }
        });

        acs_jCbonivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        acs_jCbonivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jCbonivelActionPerformed(evt);
            }
        });

        jLabel8.setText("NIVEL");

        jLabel9.setText("SENHA");

        acs_jPwfsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jPwfsenhaActionPerformed(evt);
            }
        });

        acs_jBtnincluir.setText("INCLUIR");
        acs_jBtnincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnincluirActionPerformed(evt);
            }
        });

        acs_jBtnalterar.setText("ALTERAR");
        acs_jBtnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnalterarActionPerformed(evt);
            }
        });

        acs_jBtnconfirmar.setText("CONFIRMAR");
        acs_jBtnconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnconfirmarActionPerformed(evt);
            }
        });

        acs_jBtnpesquisar.setText("PESQUISAR");

        acs_jBtnexcluir.setText("EDITAR");
        acs_jBtnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnexcluirActionPerformed(evt);
            }
        });

        acs_jBtncancelar.setText("CANCELAR");
        acs_jBtncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(acs_jTxtnome)
                    .addComponent(acs_jTxtapelido)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(acs_jFmtcpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(acs_jPwfsenha, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(acs_jFmtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(acs_jChbativo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(acs_jCbonivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(acs_jTxtcodigo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acs_jBtnincluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acs_jBtnalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acs_jBtnpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acs_jBtnconfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acs_jBtncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acs_jBtnexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acs_jTxtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acs_jTxtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acs_jTxtapelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jFmtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acs_jFmtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jCbonivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acs_jChbativo)
                    .addComponent(acs_jPwfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jBtnincluir)
                    .addComponent(acs_jBtnexcluir)
                    .addComponent(acs_jBtnpesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jBtnalterar)
                    .addComponent(acs_jBtnconfirmar)
                    .addComponent(acs_jBtncancelar))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acs_jTxtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtcodigoActionPerformed

    private void acs_jTxtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtnomeActionPerformed

    private void acs_jFmtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jFmtcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jFmtcpfActionPerformed

    private void acs_jChbativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jChbativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jChbativoActionPerformed

    private void acs_jCbonivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jCbonivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jCbonivelActionPerformed

    private void acs_jPwfsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jPwfsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jPwfsenhaActionPerformed

    private void acs_jBtnincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnincluirActionPerformed
        Util.habilitar(true, acs_jTxtcodigo, acs_jTxtnome, acs_jTxtapelido, acs_jFmtcpf, acs_jFmtdata,
                acs_jPwfsenha, acs_jCbonivel, acs_jChbativo, acs_jBtncancelar, acs_jBtnconfirmar);
        Util.habilitar(false, acs_jBtnincluir, acs_jBtnalterar, acs_jBtnexcluir, acs_jBtnexcluir);
        Util.LimparCampos(acs_jTxtcodigo, acs_jTxtnome, acs_jTxtapelido, acs_jFmtcpf, acs_jFmtdata,
                acs_jPwfsenha, acs_jCbonivel, acs_jChbativo);
        incluindo = true;

    }//GEN-LAST:event_acs_jBtnincluirActionPerformed

    private void acs_jBtnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnexcluirActionPerformed
        if (Util.perguntar("Deseja excluir o registro?") == true) {
            usuarios = viewBean();
            DaoUsuario.delete(usuarios);
        } else {

            Util.mensagem("Exclusão cancelada.");
        }

        Util.LimparCampos(acs_jTxtcodigo, acs_jTxtnome, acs_jTxtapelido, acs_jFmtcpf, acs_jFmtdata,
                acs_jPwfsenha, acs_jCbonivel, acs_jChbativo);
    }//GEN-LAST:event_acs_jBtnexcluirActionPerformed

    private void acs_jBtnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnalterarActionPerformed
        Util.habilitar(true, acs_jTxtcodigo, acs_jTxtnome, acs_jTxtapelido, acs_jFmtcpf, acs_jFmtdata,
                acs_jPwfsenha, acs_jCbonivel, acs_jChbativo, acs_jBtncancelar, acs_jBtnconfirmar);
        Util.habilitar(false, acs_jBtnincluir, acs_jBtnalterar, acs_jBtnexcluir, acs_jBtnexcluir);
        incluindo = false;
    }//GEN-LAST:event_acs_jBtnalterarActionPerformed

    private void acs_jBtnconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnconfirmarActionPerformed
        usuarios = viewBean();        
        if (incluindo == true) {
            DaoUsuario.insert(usuarios);
        } else {
            DaoUsuario.update(usuarios);
        }                
        
        Util.habilitar(false, acs_jTxtcodigo, acs_jTxtnome, acs_jTxtapelido, acs_jFmtcpf, acs_jFmtdata,
                acs_jPwfsenha, acs_jCbonivel, acs_jChbativo, acs_jBtncancelar, acs_jBtnconfirmar);
        Util.habilitar(true, acs_jBtnincluir, acs_jBtnalterar, acs_jBtnexcluir, acs_jBtnexcluir);

    }//GEN-LAST:event_acs_jBtnconfirmarActionPerformed

    private void acs_jBtncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtncancelarActionPerformed
        Util.habilitar(false, acs_jTxtcodigo, acs_jTxtnome, acs_jTxtapelido, acs_jFmtcpf, acs_jFmtdata,
                acs_jPwfsenha, acs_jCbonivel, acs_jChbativo, acs_jBtncancelar, acs_jBtnconfirmar);
        Util.habilitar(true, acs_jBtnincluir, acs_jBtnalterar, acs_jBtnexcluir, acs_jBtnexcluir);
        Util.LimparCampos(acs_jTxtcodigo, acs_jTxtnome, acs_jTxtapelido, acs_jFmtcpf, acs_jFmtdata,
                acs_jPwfsenha, acs_jCbonivel, acs_jChbativo);
    }//GEN-LAST:event_acs_jBtncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcsTelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcsTelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcsTelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcsTelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AcsTelaUsuario dialog = new AcsTelaUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acs_jBtnalterar;
    private javax.swing.JButton acs_jBtncancelar;
    private javax.swing.JButton acs_jBtnconfirmar;
    private javax.swing.JButton acs_jBtnexcluir;
    private javax.swing.JButton acs_jBtnincluir;
    private javax.swing.JButton acs_jBtnpesquisar;
    private javax.swing.JComboBox<String> acs_jCbonivel;
    private javax.swing.JCheckBox acs_jChbativo;
    private javax.swing.JFormattedTextField acs_jFmtcpf;
    private javax.swing.JFormattedTextField acs_jFmtdata;
    private javax.swing.JPasswordField acs_jPwfsenha;
    private javax.swing.JTextField acs_jTxtapelido;
    private javax.swing.JTextField acs_jTxtcodigo;
    private javax.swing.JTextField acs_jTxtnome;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
