/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import bean.AcsProduto;
import bean.AcsVendasProduto;
import dao.DaoProduto;
import dao.DaoVendas;
import dao.DaoVendasProduto;
import java.util.List;
import tools.Util;

/**
 *
 * @author ENTERPRISE
 */
public class AcsTelaVendaProduto extends javax.swing.JDialog {

    AcsTelaVenda acsTelaVendas;
    DaoProduto daoProduto;
    int NumVendaId;
    DaoVendas daoVendas;
    AcsVendasProduto acsVendasProduto;
    VendasProdutoControle vendasProdutoControle;

    /**
     * Creates new form AcsTelaVendaProduto1
     */
    public AcsTelaVendaProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Vendas Produto");
        initComponents();
         setLocationRelativeTo(null);
        daoVendas = new DaoVendas();
        Util.habilitar(false, acs_jTxttotal);
        
        DaoProduto daoproduto = new DaoProduto();
        List lista = daoproduto.listAll(); 
        for (Object item : lista) {
        acs_jCboproduto.addItem((AcsProduto) item);
        }

     
    }
    
        public void setTelaAnterior(AcsTelaVenda acsTelaVendas) {
        this.acsTelaVendas = acsTelaVendas;

  }
    
    
 public AcsVendasProduto beanView(AcsVendasProduto acsVendasProduto) {
        acs_jCboproduto.setSelectedItem(acsVendasProduto.getAcsProduto());
        acs_jTxtquantidade.setText(Integer.toString(Util.strInt(acsVendasProduto.getAcsQuantidade())));
        acs_jTxtvalor.setText(Double.toString(acsVendasProduto.getAcsValorUnitario()));
        return acsVendasProduto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        acs_jCboproduto = new javax.swing.JComboBox<AcsProduto>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        acs_jTxtquantidade = new javax.swing.JTextField();
        acs_jTxtvalor = new javax.swing.JTextField();
        acs_jBtnok = new javax.swing.JButton();
        acs_jBtncancelar = new javax.swing.JButton();
        acs_jTxttotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("PRODUTO");

        acs_jCboproduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                acs_jCboprodutoItemStateChanged(evt);
            }
        });

        jLabel2.setText("QUANTIDADE");

        jLabel3.setText("VALOR UNITÁRIO");

        acs_jTxtquantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                acs_jTxtquantidadeKeyReleased(evt);
            }
        });

        acs_jTxtvalor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                acs_jTxtvalorKeyReleased(evt);
            }
        });

        acs_jBtnok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-selecionado-20.png"))); // NOI18N
        acs_jBtnok.setText("OK");
        acs_jBtnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnokActionPerformed(evt);
            }
        });

        acs_jBtncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-excluir-20.png"))); // NOI18N
        acs_jBtncancelar.setText("CANCELAR");

        jLabel4.setText("TOTAL");

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-finalizar-pedido-64.png"))); // NOI18N
        jLabel6.setText("VENDAS PRODUTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(acs_jCboproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(248, 248, 248)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(acs_jBtnok, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(acs_jBtncancelar))
                            .addComponent(acs_jTxttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(acs_jTxtquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(acs_jTxtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(acs_jCboproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jTxtquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acs_jTxtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acs_jTxttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jBtnok)
                    .addComponent(acs_jBtncancelar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acs_jBtnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnokActionPerformed

        AcsVendasProduto acsVendasProduto = new AcsVendasProduto();
        acsVendasProduto.setAcsProduto((AcsProduto) acs_jCboproduto.getSelectedItem() );
        acsVendasProduto.setAcsQuantidade(acs_jTxtquantidade.getText() );
        acsVendasProduto.setAcsValorUnitario(Util.strDouble(acs_jTxtvalor.getText()));
        if (getTitle().toUpperCase().substring(0, 1).equals("I")) {
           acsTelaVendas.vendasProdutoControle.addBean(acsVendasProduto);
        } else {            
            acsTelaVendas.vendasProdutoControle.updateBean(acsTelaVendas.getSelectedRowProd(), acsVendasProduto);
        }
        setVisible(false);
        
    }//GEN-LAST:event_acs_jBtnokActionPerformed

    private void acs_jCboprodutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_acs_jCboprodutoItemStateChanged
        acs_jTxtquantidade.setText("1");
        AcsProduto acsProduto = (AcsProduto) acs_jCboproduto.getSelectedItem();
        acs_jTxtvalor.setText(Util.doubleStr(acsProduto.getAcsPreco()));
        acs_jTxttotal.setText(acs_jTxtvalor.getText());
    }//GEN-LAST:event_acs_jCboprodutoItemStateChanged

    private void acs_jTxtquantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acs_jTxtquantidadeKeyReleased
        if(acs_jTxtquantidade.getText().isEmpty() == false){
            double unitario = Util.strDouble(acs_jTxtvalor.getText());
            double quantidade = Util.strInt(acs_jTxtquantidade.getText());
            acs_jTxttotal.setText(Util.doubleStr(quantidade * unitario));
        } else{
        acs_jTxttotal.setText("0");
        }
        
    }//GEN-LAST:event_acs_jTxtquantidadeKeyReleased

    private void acs_jTxtvalorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acs_jTxtvalorKeyReleased
        if(acs_jTxtvalor.getText().isEmpty() == false){
            double unitario = Util.strDouble(acs_jTxtvalor.getText());
            double quantidade = Util.strInt(acs_jTxtquantidade.getText());
            acs_jTxttotal.setText(Util.doubleStr(quantidade * unitario));
        } else{
        acs_jTxttotal.setText("0");
        }
    }//GEN-LAST:event_acs_jTxtvalorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcsTelaVendaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcsTelaVendaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcsTelaVendaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcsTelaVendaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AcsTelaVendaProduto dialog = new AcsTelaVendaProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acs_jBtncancelar;
    private javax.swing.JButton acs_jBtnok;
    private javax.swing.JComboBox<AcsProduto> acs_jCboproduto;
    private javax.swing.JTextField acs_jTxtquantidade;
    private javax.swing.JTextField acs_jTxttotal;
    private javax.swing.JTextField acs_jTxtvalor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
