/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.AcsProduto;
import dao.DaoProduto;
import tools.Util;
/**
 *
 * @author ENTERPRISE
 */
public class AcsTelaProdutoIA extends javax.swing.JDialog {

    private boolean incluindo;
    public DaoProduto DaoProduto;
    /**
     * Creates new form AcsTelaPoduto
     * @param parent
     * @param modal
     */
    public AcsTelaProdutoIA(java.awt.Frame parent, boolean modal) {
       super(parent, modal);
        initComponents();
        setTitle("Incluir Produtos");
        setLocationRelativeTo(null);

    
    }
    public AcsProduto ViewBean() {
        AcsProduto acsproduto = new AcsProduto();
        
        acsproduto.setAcsIdproduto(Util.strInt(acs_jTxtcodigo.getText()));
        acsproduto.setAcsNome(acs_jTxtnome.getText());
        acsproduto.setAcsPreco(Util.strDouble(acs_jFmtpreco.getText()));
        acsproduto.setAcsAcompanhamento(acs_jTxtacompanhamento.getText());
        acsproduto.setAcsAvaliacao(Util.strDouble(acs_jTxtavaliacao.getText()));
        acsproduto.setAcsTempopreparo(acs_jCbotempo.getSelectedIndex());
        acsproduto.setAcsCategoria(acs_jCbocategoria.getSelectedIndex());
        acsproduto.setAcsPeso(acs_jTxtpeso.getText());
        acsproduto.setAcsQuantidadepessoas(Util.strInt(acs_jTxtpessoas.getText()));
        acsproduto.setAcsDescricao(acs_jTxtdescricao.getText());
        acsproduto.setAcsIngredientes(acs_jTxtingredientes.getText());
        return acsproduto;
     }
        public void beanView(AcsProduto acsproduto){
        String valor = String.valueOf(acsproduto.getAcsIdproduto());
        String avaliacao = Util.doubleStr(acsproduto.getAcsAvaliacao());
        String pessoas = String.valueOf(acsproduto.getAcsQuantidadepessoas());
        
        acs_jTxtcodigo.setText(valor);        
        acs_jTxtnome.setText(acsproduto.getAcsNome());
        acs_jTxtacompanhamento.setText(acsproduto.getAcsAcompanhamento());
        acs_jTxtavaliacao.setText(avaliacao);
        acs_jCbotempo.setSelectedIndex(acsproduto.getAcsTempopreparo());
        acs_jCbocategoria.setSelectedIndex(acsproduto.getAcsCategoria());
        acs_jTxtpeso.setText(acsproduto.getAcsPeso());
        acs_jTxtpessoas.setText(pessoas);
        acs_jTxtdescricao.setText(acsproduto.getAcsDescricao());
        acs_jTxtingredientes.setText(acsproduto.getAcsIngredientes());
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acs_jTxtcodigo = new javax.swing.JTextField();
        acs_jTxtdescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        acs_jTxtnome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        acs_jTxtacompanhamento = new javax.swing.JTextField();
        acs_jTxtingredientes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        acs_jCbotempo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        acs_jCbocategoria = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        acs_jTxtpeso = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        acs_jTxtpessoas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        acs_jFmtpreco = new javax.swing.JFormattedTextField();
        acs_jBtconfirmar = new javax.swing.JButton();
        acs_jBtncancelar = new javax.swing.JButton();
        acs_jTxtavaliacao = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-caixa-64.png"))); // NOI18N
        jLabel1.setText("PRODUTO");

        jLabel2.setText("CODIGO");

        acs_jTxtdescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtdescricaoActionPerformed(evt);
            }
        });

        jLabel3.setText("DESCRIÇÃO");

        jLabel4.setText("NOME");

        jLabel6.setText("ACOMPANHAMENTO");

        acs_jTxtacompanhamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtacompanhamentoActionPerformed(evt);
            }
        });

        acs_jTxtingredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtingredientesActionPerformed(evt);
            }
        });

        jLabel7.setText("INGREDIENTES");

        jLabel8.setText("TEMPO PREPARO");

        acs_jCbotempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 HORA", "2 HORAS", "3 HORAS", "4 HORAS" }));

        jLabel9.setText("CATEGORA");

        acs_jCbocategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIRA GOSTO", "ENTRADA", "PRINCIPAL", "SOBREMESA", "BEBIDA" }));

        jLabel10.setText("AVALIAÇÃO");

        jLabel11.setText("PESO(G)");

        jLabel12.setText("PESSOAS");

        jLabel13.setText("PREÇO");

        acs_jBtconfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-selecionado-20.png"))); // NOI18N
        acs_jBtconfirmar.setText("CONFIRMAR");
        acs_jBtconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtconfirmarActionPerformed(evt);
            }
        });

        acs_jBtncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-excluir-20.png"))); // NOI18N
        acs_jBtncancelar.setText("CANCELAR");
        acs_jBtncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(acs_jTxtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel12)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(acs_jTxtpessoas))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(acs_jCbotempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(acs_jTxtavaliacao)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(acs_jCbocategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(acs_jFmtpreco)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(acs_jTxtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(acs_jTxtacompanhamento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(acs_jTxtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acs_jBtconfirmar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(acs_jTxtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acs_jTxtingredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acs_jBtncancelar))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel3))))
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(acs_jTxtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(acs_jTxtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(acs_jTxtacompanhamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(acs_jCbocategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(acs_jTxtavaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(acs_jCbotempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(17, 17, 17)
                                .addComponent(jLabel11)
                                .addGap(35, 35, 35))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(acs_jTxtpessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acs_jFmtpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acs_jTxtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(31, 31, 31)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acs_jBtconfirmar)
                            .addComponent(acs_jBtncancelar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(acs_jTxtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(acs_jTxtingredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acs_jTxtdescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtdescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtdescricaoActionPerformed

    private void acs_jTxtacompanhamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtacompanhamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtacompanhamentoActionPerformed

    private void acs_jTxtingredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtingredientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtingredientesActionPerformed

    private void acs_jBtncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtncancelarActionPerformed
        Util.mensagem("Inclusão Cancelada");
        setVisible(false);
    }//GEN-LAST:event_acs_jBtncancelarActionPerformed

    private void acs_jBtconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtconfirmarActionPerformed
          AcsProduto acsProduto = ViewBean(); 
          DaoProduto produtoDAO = new DaoProduto();
        if (getTitle().toUpperCase().substring(0, 1).equals("I")) {
            produtoDAO.insert(acsProduto);
           
        } else {    
             produtoDAO.update(acsProduto);
        }
        setVisible(false);        
    
         Util.limparCampos(acs_jCbocategoria,acs_jCbotempo,acs_jFmtpreco,acs_jTxtacompanhamento,acs_jTxtavaliacao,acs_jTxtcodigo,acs_jTxtdescricao,acs_jTxtingredientes,acs_jTxtnome,acs_jTxtpeso,acs_jTxtpessoas);
    }//GEN-LAST:event_acs_jBtconfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcsTelaProdutoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcsTelaProdutoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcsTelaProdutoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcsTelaProdutoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AcsTelaProdutoIA dialog = new AcsTelaProdutoIA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acs_jBtconfirmar;
    private javax.swing.JButton acs_jBtncancelar;
    private javax.swing.JComboBox<String> acs_jCbocategoria;
    private javax.swing.JComboBox<String> acs_jCbotempo;
    private javax.swing.JFormattedTextField acs_jFmtpreco;
    private javax.swing.JTextField acs_jTxtacompanhamento;
    private javax.swing.JTextField acs_jTxtavaliacao;
    private javax.swing.JTextField acs_jTxtcodigo;
    private javax.swing.JTextField acs_jTxtdescricao;
    private javax.swing.JTextField acs_jTxtingredientes;
    private javax.swing.JTextField acs_jTxtnome;
    private javax.swing.JTextField acs_jTxtpeso;
    private javax.swing.JTextField acs_jTxtpessoas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
