/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import bean.AcsFuncionario;
import dao.DaoFuncionarios;
import tools.Util;

/**
 *
 * @author ENTERPRISE
 */
 /**
     * Creates new form AcsTelaFuncionario
     */
public class AcsTelaFuncionario extends javax.swing.JDialog {
    boolean incluindo;
    DaoFuncionarios daoFuncionario; 
    AcsFuncionario acsfuncionario;
    ControleFuncionario controleFuncionario;
    AcsTelaFuncionarioIA acsTelaFuncionarioIA;

    /**
     * Creates new form JDlgVendedorNsg
     * @param parent
     * @param modal
     */
    public AcsTelaFuncionario(java.awt.Frame parent, boolean modal) {
         super(parent, modal);
        initComponents();
        setTitle("Funcionario");
        setLocationRelativeTo(null);
        
       acsTelaFuncionarioIA = new AcsTelaFuncionarioIA(null, true);
        controleFuncionario = new ControleFuncionario();
        daoFuncionario = new DaoFuncionarios();
        List lista = daoFuncionario.listAll();
        controleFuncionario.setList(lista);
        jTable1.setModel(controleFuncionario);
        
    }
    
     public int getSelectedRowProd() {
        return jTable1.getSelectedRow();
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        acs_jBtnexcluir = new javax.swing.JButton();
        acs_jBtnalterar = new javax.swing.JButton();
        acs_jBtnincluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-caixa-de-ferramentas-64.png"))); // NOI18N
        jLabel1.setText("FUNCIONARIO PESQUISA");

        acs_jBtnexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-lixo-20.png"))); // NOI18N
        acs_jBtnexcluir.setText("EXCLUIR");
        acs_jBtnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnexcluirActionPerformed(evt);
            }
        });

        acs_jBtnalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-editar-20.png"))); // NOI18N
        acs_jBtnalterar.setText("ALTERAR");
        acs_jBtnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnalterarActionPerformed(evt);
            }
        });

        acs_jBtnincluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-mais-20.png"))); // NOI18N
        acs_jBtnincluir.setText("INCLUIR");
        acs_jBtnincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnincluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acs_jBtnincluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acs_jBtnalterar)
                        .addGap(61, 61, 61)
                        .addComponent(acs_jBtnexcluir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jBtnexcluir)
                    .addComponent(acs_jBtnalterar)
                    .addComponent(acs_jBtnincluir))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acs_jBtnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnalterarActionPerformed
        acsTelaFuncionarioIA.setTitle("Alterar");
        
        
        int sel = jTable1.getSelectedRow();
        AcsFuncionario acsFuncionario = controleFuncionario.getBean(sel);
        acsTelaFuncionarioIA.beanView(acsFuncionario);        
        acsTelaFuncionarioIA.setVisible(true);
        List lista = daoFuncionario.listAll();
        controleFuncionario.setList(lista);
    }//GEN-LAST:event_acs_jBtnalterarActionPerformed

    private void acs_jBtnincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnincluirActionPerformed
        incluindo = true;
        
        acsTelaFuncionarioIA.setTitle("Incluir");
        acsTelaFuncionarioIA.setVisible(true);  
        List lista = daoFuncionario.listAll();
        controleFuncionario.setList(lista);
        
    }//GEN-LAST:event_acs_jBtnincluirActionPerformed

    private void acs_jBtnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnexcluirActionPerformed
        if (Util.perguntar("Deseja demitir este funcionario?") == true){
            int sel = jTable1.getSelectedRow();
            AcsFuncionario acsFuncionario = controleFuncionario.getBean(sel);
            daoFuncionario.delete(acsFuncionario);
            List lista = daoFuncionario.listAll();
            controleFuncionario.setList(lista);
        } else{
            Util.mensagem("Exclusão cancelada");
        }
    }//GEN-LAST:event_acs_jBtnexcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcsTelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcsTelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcsTelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcsTelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AcsTelaFuncionario dialog = new AcsTelaFuncionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acs_jBtnalterar;
    private javax.swing.JButton acs_jBtnexcluir;
    private javax.swing.JButton acs_jBtnincluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
