/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.AcsProduto;
import dao.DaoProduto;
import tools.Util;
import java.util.List;

/**
 *
 * @author ENTERPRISE
 */
public class AcsTelaProduto extends javax.swing.JDialog {
    boolean incluindo;
    DaoProduto daoproduto; 
    AcsProduto acsproduto;
    ProdutoControle produtocontrole;
    AcsTelaProdutoIA acstelaprodutoia;
    AcsProduto acsProduto;
    /**
     * Creates new form AcsTelaFuncionario
     */
    public AcsTelaProduto(java.awt.Frame parent, boolean modal) {  
         super(parent, modal);
         initComponents();
         setTitle("Produto");
         setLocationRelativeTo(null);
         
         acstelaprodutoia = new AcsTelaProdutoIA(null, true);
         daoproduto = new DaoProduto();
         List lista = daoproduto.listAll();
         produtocontrole = new ProdutoControle();
         produtocontrole.setList(lista);
         jTable1.setModel(produtocontrole);
    }
        public int getSelectedRowProd() {
        return jTable1.getSelectedRow();
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        acs_jBtnexcluir = new javax.swing.JButton();
        acs_jBtnalterar = new javax.swing.JButton();
        acs_jBtnincluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-caixa-64.png"))); // NOI18N
        jLabel1.setText("PRODUTO PESQUISA");

        acs_jBtnexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-lixo-20.png"))); // NOI18N
        acs_jBtnexcluir.setText("EXCLUIR");
        acs_jBtnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnexcluirActionPerformed(evt);
            }
        });

        acs_jBtnalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-editar-20.png"))); // NOI18N
        acs_jBtnalterar.setText("ALTERAR");
        acs_jBtnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnalterarActionPerformed(evt);
            }
        });

        acs_jBtnincluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-mais-20.png"))); // NOI18N
        acs_jBtnincluir.setText("INCLUIR");
        acs_jBtnincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnincluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acs_jBtnincluir)
                        .addGap(73, 73, 73)
                        .addComponent(acs_jBtnalterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acs_jBtnexcluir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jBtnexcluir)
                    .addComponent(acs_jBtnalterar)
                    .addComponent(acs_jBtnincluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acs_jBtnincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnincluirActionPerformed
       
       acstelaprodutoia.setTitle("Incluir");
       acstelaprodutoia.setVisible(true);
       List lista = daoproduto.listAll();
       produtocontrole.setList(lista);
        
    }//GEN-LAST:event_acs_jBtnincluirActionPerformed

    private void acs_jBtnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnexcluirActionPerformed
        if (Util.perguntar("Deseja excluir este produto?") == true){
            int sel = jTable1.getSelectedRow();
            AcsProduto acsproduto = produtocontrole.getBean(sel);
            daoproduto.delete(acsproduto);
            List lista = daoproduto.listAll();
            produtocontrole.setList(lista);
            Util.mensagem("Exclusão Concluída");
        } else{
            Util.mensagem("Exclusão cancelada");
        }
    }//GEN-LAST:event_acs_jBtnexcluirActionPerformed

    private void acs_jBtnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnalterarActionPerformed
        acstelaprodutoia.setTitle("Alterar");
        
        
        int sel = jTable1.getSelectedRow();
        acsProduto = produtocontrole.getBean(sel);
        acstelaprodutoia.beanView(acsProduto);        
        acstelaprodutoia.setVisible(true);

        List lista = daoproduto.listAll();
        produtocontrole.setList(lista);
    }//GEN-LAST:event_acs_jBtnalterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcsTelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcsTelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcsTelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcsTelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AcsTelaProduto dialog = new AcsTelaProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acs_jBtnalterar;
    private javax.swing.JButton acs_jBtnexcluir;
    private javax.swing.JButton acs_jBtnincluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
