/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.AcsFuncionario;
import dao.DaoFuncionarios;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author ENTERPRISE
 */
public class AcsTelaFuncionarioIA extends javax.swing.JDialog {

    private boolean incluindo;
    MaskFormatter mascaraCPF;
    public AcsFuncionario funcionario;
    public DaoFuncionarios DaoFuncionarios;
    
    /**
     * Creates new form AcsTelaFuncionarioIA
     * @param parent
     * @param modal
     */
    public AcsTelaFuncionarioIA(java.awt.Frame parent, boolean modal) {
       super(parent, modal);
        initComponents();
        setTitle("Funcionários");
        setLocationRelativeTo(null);
        DaoFuncionarios = new DaoFuncionarios();
        try {
            mascaraCPF = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
            Logger.getLogger(AcsTelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        acs_jFmtcpf.setFormatterFactory(new DefaultFormatterFactory(mascaraCPF));  
    }
    
         public AcsFuncionario ViewBean() {
        AcsFuncionario acsfuncionario = new AcsFuncionario();
        
        
        acsfuncionario.setAcsIdfuncionario(Util.strInt(acs_jTxtcodigo.getText()));
        acsfuncionario.setAcsNome(acs_jTxtnome.getText());
        acsfuncionario.setAcsCpf(acs_jFmtcpf.getText());
        acsfuncionario.setAcsEndereco(acs_jTxtendereco.getText());
        acsfuncionario.setAcsFuncao(acs_jTxtfuncao.getText());
        return acsfuncionario;
     }
         
        public void beanView(AcsFuncionario acsfuncionario){
        String valor = String.valueOf(acsfuncionario.getAcsIdfuncionario());
        acs_jTxtcodigo.setText(valor);        
        acs_jTxtnome.setText(acsfuncionario.getAcsNome());
        acs_jFmtcpf.setText(acsfuncionario.getAcsCpf());
        acs_jTxtendereco.setText(acsfuncionario.getAcsEndereco());
        acs_jTxtfuncao.setText(acsfuncionario.getAcsFuncao());
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acs_jTxtcodigo = new javax.swing.JTextField();
        acs_jTxtendereco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        acs_jFmtcpf = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        acs_jTxtnome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        acs_jBtnconfirmar = new javax.swing.JButton();
        acs_jBtncancelar = new javax.swing.JButton();
        acs_jTxtfuncao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-caixa-de-ferramentas-20.png"))); // NOI18N
        jLabel1.setText("FUNCIONÁRIO");

        jLabel2.setText("CODIGO");

        acs_jTxtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtcodigoActionPerformed(evt);
            }
        });

        acs_jTxtendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtenderecoActionPerformed(evt);
            }
        });

        jLabel4.setText("ENDEREÇO");

        jLabel5.setText("CPF");

        jLabel6.setText("FUNÇÃO");

        acs_jTxtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtnomeActionPerformed(evt);
            }
        });

        jLabel8.setText("NOME");

        acs_jBtnconfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-selecionado-20.png"))); // NOI18N
        acs_jBtnconfirmar.setText("CONFIRMAR");
        acs_jBtnconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnconfirmarActionPerformed(evt);
            }
        });

        acs_jBtncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-excluir-20.png"))); // NOI18N
        acs_jBtncancelar.setText("CANCELAR");
        acs_jBtncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(acs_jTxtendereco, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(acs_jFmtcpf)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(acs_jTxtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(acs_jTxtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(acs_jBtnconfirmar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(acs_jBtncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(acs_jTxtfuncao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 61, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acs_jTxtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acs_jTxtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acs_jTxtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acs_jFmtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(acs_jTxtfuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jBtnconfirmar)
                    .addComponent(acs_jBtncancelar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acs_jTxtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtcodigoActionPerformed

    private void acs_jTxtenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtenderecoActionPerformed

    private void acs_jTxtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtnomeActionPerformed

    private void acs_jBtncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtncancelarActionPerformed
        Util.mensagem("Inclusão Cancelada");
        setVisible(false);
    }//GEN-LAST:event_acs_jBtncancelarActionPerformed

    private void acs_jBtnconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnconfirmarActionPerformed
        AcsFuncionario acsfuncionario = ViewBean();
        DaoFuncionarios daofuncionario = new DaoFuncionarios();
        daofuncionario.insert(acsfuncionario);

         Util.limparCampos(acs_jTxtcodigo, acs_jFmtcpf,acs_jTxtnome, acs_jTxtendereco, acs_jTxtfuncao); 
         Util.mensagem("Funcionario Cadastrado");
         setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jBtnconfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcsTelaFuncionarioIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcsTelaFuncionarioIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcsTelaFuncionarioIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcsTelaFuncionarioIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AcsTelaFuncionarioIA dialog = new AcsTelaFuncionarioIA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acs_jBtncancelar;
    private javax.swing.JButton acs_jBtnconfirmar;
    private javax.swing.JFormattedTextField acs_jFmtcpf;
    private javax.swing.JTextField acs_jTxtcodigo;
    private javax.swing.JTextField acs_jTxtendereco;
    private javax.swing.JTextField acs_jTxtfuncao;
    private javax.swing.JTextField acs_jTxtnome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
