/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author u09564875137
 */
public class AcsTelaClienteIA extends javax.swing.JDialog {

    /**
     * Creates new form AcsTelaCliente
     */
    public AcsTelaClienteIA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acs_jTxtcodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        acs_jTxtnome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        acs_jFmtcpf = new javax.swing.JFormattedTextField();
        acs_jTxtemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        acs_jFmtrg = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        acs_jFmtdata = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        acs_jTxtendereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        acs_jFmtcep = new javax.swing.JFormattedTextField();
        acs_jTxtcidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        acs_jTxtNumero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        acs_jTxtnacionalidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        acs_jFmtcelular = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        acs_jCboestadocivil = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        acs_jTxtsexo = new javax.swing.JTextField();
        acs_jBtnincluir = new javax.swing.JButton();
        acs_jbtneditar = new javax.swing.JButton();
        acs_jbtnpesquisar = new javax.swing.JButton();
        acs_jBtnalterar = new javax.swing.JButton();
        acs_jbtncancelar = new javax.swing.JButton();
        acs_jBtnconfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CLIENTE");

        jLabel2.setText("CODIGO");

        acs_jTxtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtcodigoActionPerformed(evt);
            }
        });

        jLabel3.setText("NOME");

        acs_jTxtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtnomeActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF");

        acs_jFmtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jFmtcpfActionPerformed(evt);
            }
        });

        acs_jTxtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtemailActionPerformed(evt);
            }
        });

        jLabel5.setText("RG");

        acs_jFmtrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jFmtrgActionPerformed(evt);
            }
        });

        jLabel6.setText("DATA NASCIMENTO");

        jLabel7.setText("EMAIL");

        jLabel8.setText("CEP");

        jLabel9.setText("ENDEREÇO");

        acs_jTxtendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtenderecoActionPerformed(evt);
            }
        });

        jLabel10.setText("CIDADE");

        acs_jFmtcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jFmtcepActionPerformed(evt);
            }
        });

        jLabel11.setText("NÚMERO");

        acs_jTxtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtNumeroActionPerformed(evt);
            }
        });

        jLabel12.setText("NACIONALIDADE");

        jLabel13.setText("CELULAR");

        jLabel14.setText("ESTADO CIVÍL");

        acs_jCboestadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        acs_jCboestadocivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jCboestadocivilActionPerformed(evt);
            }
        });

        jLabel15.setText("SEXO");

        acs_jTxtsexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtsexoActionPerformed(evt);
            }
        });

        acs_jBtnincluir.setText("INCLUIR");

        acs_jbtneditar.setText("EDITAR");

        acs_jbtnpesquisar.setText("PESQUISAR");

        acs_jBtnalterar.setText("ALTERAR");
        acs_jBtnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnalterarActionPerformed(evt);
            }
        });

        acs_jbtncancelar.setText("CANCELAR");

        acs_jBtnconfirmar.setText("CNFIRMAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acs_jBtnalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acs_jBtnconfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(acs_jbtncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(acs_jCboestadocivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(acs_jTxtnacionalidade)
                            .addComponent(acs_jTxtcidade)
                            .addComponent(acs_jFmtcep)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acs_jTxtcodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acs_jTxtnome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acs_jFmtcpf, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(acs_jFmtrg, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(acs_jTxtemail)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(acs_jFmtdata, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(acs_jTxtendereco, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(acs_jTxtNumero, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(acs_jFmtcelular, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(acs_jTxtsexo, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acs_jBtnincluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(acs_jbtnpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(acs_jbtneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acs_jTxtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(acs_jTxtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(acs_jFmtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7)
                                .addGap(11, 11, 11)
                                .addComponent(acs_jTxtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(acs_jFmtrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(acs_jFmtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jTxtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acs_jFmtcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jTxtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acs_jTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jTxtnacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acs_jFmtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jCboestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acs_jTxtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jbtnpesquisar)
                    .addComponent(acs_jBtnincluir)
                    .addComponent(acs_jbtneditar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jBtnconfirmar)
                    .addComponent(acs_jBtnalterar)
                    .addComponent(acs_jbtncancelar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acs_jTxtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtcodigoActionPerformed

    private void acs_jTxtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtnomeActionPerformed

    private void acs_jFmtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jFmtcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jFmtcpfActionPerformed

    private void acs_jTxtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtemailActionPerformed

    private void acs_jFmtrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jFmtrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jFmtrgActionPerformed

    private void acs_jCboestadocivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jCboestadocivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jCboestadocivilActionPerformed

    private void acs_jTxtsexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtsexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtsexoActionPerformed

    private void acs_jFmtcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jFmtcepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jFmtcepActionPerformed

    private void acs_jTxtenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtenderecoActionPerformed

    private void acs_jTxtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtNumeroActionPerformed

    private void acs_jBtnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnalterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jBtnalterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcsTelaClienteIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcsTelaClienteIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcsTelaClienteIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcsTelaClienteIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AcsTelaClienteIA dialog = new AcsTelaClienteIA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acs_jBtnalterar;
    private javax.swing.JButton acs_jBtnconfirmar;
    private javax.swing.JButton acs_jBtnincluir;
    private javax.swing.JComboBox<String> acs_jCboestadocivil;
    private javax.swing.JFormattedTextField acs_jFmtcelular;
    private javax.swing.JFormattedTextField acs_jFmtcep;
    private javax.swing.JFormattedTextField acs_jFmtcpf;
    private javax.swing.JFormattedTextField acs_jFmtdata;
    private javax.swing.JFormattedTextField acs_jFmtrg;
    private javax.swing.JTextField acs_jTxtNumero;
    private javax.swing.JTextField acs_jTxtcidade;
    private javax.swing.JTextField acs_jTxtcodigo;
    private javax.swing.JTextField acs_jTxtemail;
    private javax.swing.JTextField acs_jTxtendereco;
    private javax.swing.JTextField acs_jTxtnacionalidade;
    private javax.swing.JTextField acs_jTxtnome;
    private javax.swing.JTextField acs_jTxtsexo;
    private javax.swing.JButton acs_jbtncancelar;
    private javax.swing.JButton acs_jbtneditar;
    private javax.swing.JButton acs_jbtnpesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
