/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.AcsCliente;
import dao.DaoCliente;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author u09564875137
 */
public class AcsTelaCliente extends javax.swing.JDialog {
    
     MaskFormatter mascaraCPF, mascaraData,mascaraRG, mascaraCEP,mascaraCelular;
     private boolean incluindo;
     public DaoCliente DaoCliente;
     public AcsCliente clientes;

    /**
     *
     */

    /**
     * Creates new form AcsTelaCliente
     * @param parent
     * @param modal
     */
    public AcsTelaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Clientes");
        setLocationRelativeTo(null);
        DaoCliente = new DaoCliente();
        Util.habilitar(false,acs_jBtnconfirmar,acs_jCboestadocivil,acs_jFmtcelular,acs_jFmtcep,acs_jFmtcpf,acs_jFmtdata,acs_jFmtrg,acs_jTxtNumero,acs_jTxtcidade,acs_jTxtcodigo,acs_jTxtemail,acs_jTxtendereco,acs_jTxtnacionalidade,acs_jTxtnome,acs_jTxtsexo,acs_jbtncancelar);
   
    try {
        mascaraCPF = new MaskFormatter("###.###.###-##");
        mascaraData = new MaskFormatter("##/##/####");
        mascaraRG = new MaskFormatter("#.###.###");
        mascaraCEP = new MaskFormatter("#####-###");
        mascaraCelular = new MaskFormatter("(##)#####-####");
    } catch (ParseException ex) {
        Logger.getLogger(AcsTelaCliente.class.getName()).log(Level.SEVERE, null, ex);
    }
         acs_jFmtcpf.setFormatterFactory(new DefaultFormatterFactory(mascaraCPF));
         acs_jFmtdata.setFormatterFactory(new DefaultFormatterFactory(mascaraData));   
         acs_jFmtcep.setFormatterFactory(new DefaultFormatterFactory(mascaraCEP));
         acs_jFmtrg.setFormatterFactory(new DefaultFormatterFactory(mascaraRG));
         acs_jFmtcelular.setFormatterFactory(new DefaultFormatterFactory(mascaraCelular));
        
    }
    public AcsCliente ViewBean() {
        AcsCliente acscliente = new AcsCliente();
        
        acscliente.setAcsIdcliente(Util.strInt(acs_jTxtcodigo.getText()));
        acscliente.setAcsNome(acs_jTxtnome.getText());
        acscliente.setAcsCpf(acs_jFmtcpf.getText());
        acscliente.setAcsRg(acs_jFmtrg.getText());         
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    try {
        acscliente.setAcsDataNasc(formato.parse(acs_jFmtdata.getText()));
    } catch (ParseException ex) {
        Logger.getLogger(AcsTelaCliente.class.getName()).log(Level.SEVERE, null, ex);
    }
    
        acscliente.setAcsEmail(acs_jTxtemail.getText());
        acscliente.setAcsCep(acs_jFmtcep.getText());
        acscliente.setAcsEndereco(acs_jTxtendereco.getText());
        acscliente.setAcsCidade(acs_jTxtcidade.getText());
        acscliente.setAcsNumeroCasa(Util.strInt(acs_jTxtNumero.getText()));
        acscliente.setAcsNacionalidade(acs_jTxtnacionalidade.getText());
        acscliente.setAcsCelular(acs_jFmtcelular.getText());
        acscliente.setAcsEstadoCivil(acs_jCboestadocivil.getSelectedIndex());
        acscliente.setAcsSexo(acs_jTxtsexo.getText());
        
        return acscliente;
     }
     public void beanView(AcsCliente acscliente){
              
        acs_jTxtcodigo.setText(Util.intStr(acscliente.getAcsIdcliente()));
        acs_jTxtnome.setText(acscliente.getAcsNome());
        acs_jFmtcpf.setText(acscliente.getAcsCpf());
        acs_jFmtrg.setText(acscliente.getAcsRg());
        acs_jFmtdata.setText(Util.dateStr(acscliente.getAcsDataNasc()));
        acs_jFmtcep.setText(acscliente.getAcsCep());
        acs_jTxtemail.setText(acscliente.getAcsEmail());
        acs_jTxtendereco.setText(acscliente.getAcsEndereco());
        acs_jTxtcidade.setText(acscliente.getAcsCidade());
        acs_jTxtNumero.setText(Util.intStr(acscliente.getAcsNumeroCasa()));
        acs_jTxtnacionalidade.setText(acscliente.getAcsNacionalidade());
        acs_jFmtcelular.setText(acscliente.getAcsCelular());
        acs_jCboestadocivil.setSelectedIndex(acscliente.getAcsEstadoCivil());
        acs_jTxtsexo.setText(acscliente.getAcsSexo());
    } 
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acs_jTxtcodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        acs_jTxtnome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        acs_jFmtcpf = new javax.swing.JFormattedTextField();
        acs_jTxtemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        acs_jFmtrg = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        acs_jFmtdata = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        acs_jTxtendereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        acs_jFmtcep = new javax.swing.JFormattedTextField();
        acs_jTxtcidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        acs_jTxtNumero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        acs_jTxtnacionalidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        acs_jFmtcelular = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        acs_jCboestadocivil = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        acs_jBtnincluir = new javax.swing.JButton();
        acs_jbtnexcluir = new javax.swing.JButton();
        acs_jbtnpesquisar = new javax.swing.JButton();
        acs_jBtnalterar = new javax.swing.JButton();
        acs_jbtncancelar = new javax.swing.JButton();
        acs_jBtnconfirmar = new javax.swing.JButton();
        acs_jTxtsexo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-myspace-20.png"))); // NOI18N
        jLabel1.setText("CLIENTE");

        jLabel2.setText("CODIGO");

        acs_jTxtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtcodigoActionPerformed(evt);
            }
        });

        jLabel3.setText("NOME");

        acs_jTxtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtnomeActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF");

        acs_jFmtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jFmtcpfActionPerformed(evt);
            }
        });

        acs_jTxtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtemailActionPerformed(evt);
            }
        });

        jLabel5.setText("RG");

        acs_jFmtrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jFmtrgActionPerformed(evt);
            }
        });

        jLabel6.setText("DATA NASCIMENTO");

        jLabel7.setText("EMAIL");

        jLabel8.setText("CEP");

        jLabel9.setText("ENDEREÇO");

        acs_jTxtendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtenderecoActionPerformed(evt);
            }
        });

        jLabel10.setText("CIDADE");

        acs_jFmtcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jFmtcepActionPerformed(evt);
            }
        });

        jLabel11.setText("NÚMERO");

        acs_jTxtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jTxtNumeroActionPerformed(evt);
            }
        });

        jLabel12.setText("NACIONALIDADE");

        jLabel13.setText("CELULAR");

        jLabel14.setText("ESTADO CIVÍL");

        acs_jCboestadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado", "Divorciado", "Viúvo", "União Estável" }));
        acs_jCboestadocivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jCboestadocivilActionPerformed(evt);
            }
        });

        jLabel15.setText("SEXO");

        acs_jBtnincluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-mais-20.png"))); // NOI18N
        acs_jBtnincluir.setText("INCLUIR");
        acs_jBtnincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnincluirActionPerformed(evt);
            }
        });

        acs_jbtnexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-lixo-20.png"))); // NOI18N
        acs_jbtnexcluir.setText("EXCLUIR");
        acs_jbtnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jbtnexcluirActionPerformed(evt);
            }
        });

        acs_jbtnpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pesquisar-20.png"))); // NOI18N
        acs_jbtnpesquisar.setText("PESQUISAR");
        acs_jbtnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jbtnpesquisarActionPerformed(evt);
            }
        });

        acs_jBtnalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-editar-20.png"))); // NOI18N
        acs_jBtnalterar.setText("ALTERAR");
        acs_jBtnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnalterarActionPerformed(evt);
            }
        });

        acs_jbtncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-excluir-20.png"))); // NOI18N
        acs_jbtncancelar.setText("CANCELAR");
        acs_jbtncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jbtncancelarActionPerformed(evt);
            }
        });

        acs_jBtnconfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-selecionado-20.png"))); // NOI18N
        acs_jBtnconfirmar.setText("CONFIRMAR");
        acs_jBtnconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acs_jBtnconfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acs_jBtnalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acs_jBtnconfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(acs_jbtncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(acs_jCboestadocivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(acs_jTxtnacionalidade)
                            .addComponent(acs_jTxtcidade)
                            .addComponent(acs_jFmtcep)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acs_jTxtcodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acs_jTxtnome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acs_jFmtcpf, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(acs_jFmtrg, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(acs_jTxtemail)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(acs_jFmtdata, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(acs_jTxtendereco, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(acs_jTxtNumero, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(acs_jFmtcelular, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(acs_jTxtsexo)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acs_jBtnincluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(acs_jbtnpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(acs_jbtnexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acs_jTxtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(acs_jTxtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(acs_jFmtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7)
                                .addGap(11, 11, 11)
                                .addComponent(acs_jTxtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(acs_jFmtrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(acs_jFmtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jTxtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acs_jFmtcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jTxtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acs_jTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jTxtnacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acs_jFmtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jCboestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acs_jTxtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jbtnpesquisar)
                    .addComponent(acs_jBtnincluir)
                    .addComponent(acs_jbtnexcluir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acs_jBtnconfirmar)
                    .addComponent(acs_jBtnalterar)
                    .addComponent(acs_jbtncancelar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acs_jTxtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtcodigoActionPerformed

    private void acs_jTxtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtnomeActionPerformed

    private void acs_jFmtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jFmtcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jFmtcpfActionPerformed

    private void acs_jTxtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtemailActionPerformed

    private void acs_jFmtrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jFmtrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jFmtrgActionPerformed

    private void acs_jCboestadocivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jCboestadocivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jCboestadocivilActionPerformed

    private void acs_jFmtcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jFmtcepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jFmtcepActionPerformed

    private void acs_jTxtenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtenderecoActionPerformed

    private void acs_jTxtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jTxtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jTxtNumeroActionPerformed

    private void acs_jBtnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnalterarActionPerformed
       Util.habilitar(true,acs_jTxtcodigo, acs_jTxtnacionalidade,acs_jTxtnome, acs_jTxtNumero,acs_jTxtendereco,acs_jTxtcidade,acs_jFmtcpf,acs_jFmtcelular,acs_jFmtcep,acs_jFmtdata,acs_jTxtemail,acs_jFmtrg, acs_jCboestadocivil,acs_jTxtsexo, acs_jBtnconfirmar,acs_jbtncancelar);
       Util.habilitar(false,acs_jBtnalterar,acs_jbtnexcluir,acs_jbtnpesquisar,acs_jBtnincluir );
       incluindo = false;         // TODO add your handling code here:
    }//GEN-LAST:event_acs_jBtnalterarActionPerformed

    private void acs_jBtnincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnincluirActionPerformed
       Util.habilitar(true,acs_jTxtcodigo, acs_jTxtnacionalidade,acs_jTxtnome, acs_jTxtNumero,acs_jTxtendereco,acs_jTxtcidade,acs_jFmtcpf,acs_jFmtcelular,acs_jFmtcep,acs_jFmtdata,acs_jTxtemail,acs_jFmtrg, acs_jCboestadocivil,acs_jTxtsexo, acs_jBtnconfirmar,acs_jbtncancelar);
       Util.habilitar(false,acs_jBtnalterar,acs_jbtnexcluir,acs_jbtnpesquisar,acs_jBtnincluir );
       Util.limparCampos(acs_jTxtcidade, acs_jTxtcodigo, acs_jTxtemail, acs_jTxtendereco, acs_jTxtnacionalidade, acs_jTxtnome,acs_jTxtNumero, acs_jFmtcpf, acs_jFmtcelular, acs_jFmtcep, acs_jFmtdata, acs_jFmtrg,  acs_jCboestadocivil, acs_jTxtsexo);
       incluindo = true;        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jBtnincluirActionPerformed

    private void acs_jBtnconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jBtnconfirmarActionPerformed
       Util.habilitar(false,acs_jTxtcodigo, acs_jTxtnacionalidade,acs_jTxtnome, acs_jTxtNumero,acs_jTxtendereco,acs_jTxtcidade,acs_jFmtcpf,acs_jFmtcelular,acs_jFmtcep,acs_jFmtdata,acs_jTxtemail,acs_jFmtrg, acs_jCboestadocivil,acs_jTxtsexo, acs_jBtnconfirmar,acs_jbtncancelar);
       Util.habilitar(true,acs_jBtnalterar,acs_jbtnexcluir,acs_jbtnpesquisar,acs_jBtnincluir );
       
        AcsCliente acscliente = ViewBean();
        DaoCliente daocliente = new DaoCliente();
        
        if (incluindo == true) {
            daocliente.insert(acscliente);
        } else {
            daocliente.update(acscliente);
        }
       Util.limparCampos(acs_jTxtcidade, acs_jTxtcodigo, acs_jTxtemail, acs_jTxtendereco, acs_jTxtnacionalidade, acs_jTxtnome,acs_jTxtNumero, acs_jFmtcpf, acs_jFmtcelular, acs_jFmtcep, acs_jFmtdata, acs_jFmtrg,  acs_jCboestadocivil, acs_jTxtsexo);        // TODO add your handling code here:
    }//GEN-LAST:event_acs_jBtnconfirmarActionPerformed

    private void acs_jbtncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jbtncancelarActionPerformed
       Util.habilitar(false,acs_jTxtcodigo, acs_jTxtnacionalidade,acs_jTxtnome, acs_jTxtNumero,acs_jTxtendereco,acs_jTxtcidade,acs_jFmtcpf,acs_jFmtcelular,acs_jFmtcep,acs_jFmtdata,acs_jTxtemail,acs_jFmtrg, acs_jCboestadocivil,acs_jTxtsexo, acs_jBtnconfirmar,acs_jbtncancelar);
       Util.habilitar(true,acs_jBtnalterar,acs_jbtnexcluir,acs_jbtnpesquisar,acs_jBtnincluir );
       Util.limparCampos(acs_jTxtcidade, acs_jTxtcodigo, acs_jTxtemail, acs_jTxtendereco, acs_jTxtnacionalidade, acs_jTxtnome,acs_jTxtNumero, acs_jFmtcpf, acs_jFmtcelular, acs_jFmtcep, acs_jFmtdata, acs_jFmtrg,  acs_jCboestadocivil, acs_jTxtsexo);
       
    }//GEN-LAST:event_acs_jbtncancelarActionPerformed

    private void acs_jbtnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jbtnexcluirActionPerformed
         if (Util.perguntar("Deseja excluir o registro?") == true){
            AcsCliente cliente = ViewBean();
            DaoCliente clientedao = new DaoCliente();
            clientedao.delete(cliente);
       }else {
                Util.mensagem("Exclusão cancelada.");
                }  
         Util.limparCampos(acs_jTxtcidade, acs_jTxtcodigo, acs_jTxtemail, acs_jTxtendereco, acs_jTxtnacionalidade, acs_jTxtnome,acs_jTxtNumero, acs_jFmtcpf, acs_jFmtcelular, acs_jFmtcep, acs_jFmtdata, acs_jFmtrg,  acs_jCboestadocivil, acs_jTxtsexo);

    }//GEN-LAST:event_acs_jbtnexcluirActionPerformed

    private void acs_jbtnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acs_jbtnpesquisarActionPerformed
        Util.limparCampos(acs_jTxtcidade, acs_jTxtcodigo, acs_jTxtemail, acs_jTxtendereco, acs_jTxtnacionalidade, acs_jTxtnome,acs_jTxtNumero, acs_jFmtcpf, acs_jFmtcelular, acs_jFmtcep, acs_jFmtdata, acs_jFmtrg,  acs_jCboestadocivil, acs_jTxtsexo);
        AcsTelaClientePesquisar acsTelaClientePesquisar = new AcsTelaClientePesquisar(null, true);
        acsTelaClientePesquisar.setTelaAnterior(this);     
        acsTelaClientePesquisar.setVisible(true);
        
    }//GEN-LAST:event_acs_jbtnpesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcsTelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcsTelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcsTelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcsTelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AcsTelaCliente dialog = new AcsTelaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acs_jBtnalterar;
    private javax.swing.JButton acs_jBtnconfirmar;
    private javax.swing.JButton acs_jBtnincluir;
    private javax.swing.JComboBox<String> acs_jCboestadocivil;
    private javax.swing.JFormattedTextField acs_jFmtcelular;
    private javax.swing.JFormattedTextField acs_jFmtcep;
    private javax.swing.JFormattedTextField acs_jFmtcpf;
    private javax.swing.JFormattedTextField acs_jFmtdata;
    private javax.swing.JFormattedTextField acs_jFmtrg;
    private javax.swing.JTextField acs_jTxtNumero;
    private javax.swing.JTextField acs_jTxtcidade;
    private javax.swing.JTextField acs_jTxtcodigo;
    private javax.swing.JTextField acs_jTxtemail;
    private javax.swing.JTextField acs_jTxtendereco;
    private javax.swing.JTextField acs_jTxtnacionalidade;
    private javax.swing.JTextField acs_jTxtnome;
    private javax.swing.JTextField acs_jTxtsexo;
    private javax.swing.JButton acs_jbtncancelar;
    private javax.swing.JButton acs_jbtnexcluir;
    private javax.swing.JButton acs_jbtnpesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
