package bean;
// Generated 08/12/2023 16:14:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AcsFuncionario generated by hbm2java
 */
@Entity
@Table(name="acs_funcionario"
    ,catalog="db_alan_batista"
)
public class AcsFuncionario  implements java.io.Serializable {


     private int acsIdfuncionario;
     private String acsNome;
     private String acsFuncao;
     private String acsCpf;
     private String acsEndereco;

    public AcsFuncionario() {
    }

	
    public AcsFuncionario(int acsIdfuncionario, String acsNome, String acsFuncao, String acsCpf, String acsEndereco) {
        this.acsIdfuncionario = acsIdfuncionario;
        this.acsNome = acsNome;
        this.acsFuncao = acsFuncao;
        this.acsCpf = acsCpf;
        this.acsEndereco = acsEndereco;
    }
    public AcsFuncionario(int acsIdfuncionario, String acsNome, String acsFuncao, String acsCpf, String acsEndereco, Set acsVendases) {
       this.acsIdfuncionario = acsIdfuncionario;
       this.acsNome = acsNome;
       this.acsFuncao = acsFuncao;
       this.acsCpf = acsCpf;
       this.acsEndereco = acsEndereco;
    }
   
     @Id 

    
    @Column(name="acs_idfuncionario", unique=true, nullable=false)
    public int getAcsIdfuncionario() {
        return this.acsIdfuncionario;
    }
    
    public void setAcsIdfuncionario(int acsIdfuncionario) {
        this.acsIdfuncionario = acsIdfuncionario;
    }

    
    @Column(name="acs_nome", nullable=false, length=45)
    public String getAcsNome() {
        return this.acsNome;
    }
    
    public void setAcsNome(String acsNome) {
        this.acsNome = acsNome;
    }

    
    @Column(name="acs_funcao", nullable=false, length=150)
    public String getAcsFuncao() {
        return this.acsFuncao;
    }
    
    public void setAcsFuncao(String acsFuncao) {
        this.acsFuncao = acsFuncao;
    }

    
    @Column(name="acs_cpf", nullable=false, length=45)
    public String getAcsCpf() {
        return this.acsCpf;
    }
    
    public void setAcsCpf(String acsCpf) {
        this.acsCpf = acsCpf;
    }

    
    @Column(name="acs_endereco", nullable=false, length=11)
    public String getAcsEndereco() {
        return this.acsEndereco;
    }
    
    public void setAcsEndereco(String acsEndereco) {
        this.acsEndereco = acsEndereco;
    }
            @Override
     public String toString() {
    return acsNome;
}
    
         @Override
      public boolean equals (Object object){
      if(object instanceof AcsFuncionario){
      AcsFuncionario acsFuncionario = (AcsFuncionario) object;
        if(this.getAcsIdfuncionario()== acsFuncionario.getAcsIdfuncionario())
            return true;
                }         
                return false;
      }

}


