package bean;
// Generated 16/09/2023 13:12:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AcsPedioPrato generated by hbm2java
 */
@Entity
@Table(name="acs_pedio_prato"
    ,catalog="db_alan_batista"
)
public class AcsPedioPrato  implements java.io.Serializable {


     private int acsIdpedidoPrato;
     private Integer acsPedido;
     private Integer acsPrato;
     private String acsQuantidade;
     private BigDecimal acsValorUnitario;

    public AcsPedioPrato() {
    }

	
    public AcsPedioPrato(int acsIdpedidoPrato, String acsQuantidade, BigDecimal acsValorUnitario) {
        this.acsIdpedidoPrato = acsIdpedidoPrato;
        this.acsQuantidade = acsQuantidade;
        this.acsValorUnitario = acsValorUnitario;
    }
    public AcsPedioPrato(int acsIdpedidoPrato, Integer acsPedido, Integer acsPrato, String acsQuantidade, BigDecimal acsValorUnitario) {
       this.acsIdpedidoPrato = acsIdpedidoPrato;
       this.acsPedido = acsPedido;
       this.acsPrato = acsPrato;
       this.acsQuantidade = acsQuantidade;
       this.acsValorUnitario = acsValorUnitario;
    }
   
     @Id 

    
    @Column(name="acs_idpedido_prato", unique=true, nullable=false)
    public int getAcsIdpedidoPrato() {
        return this.acsIdpedidoPrato;
    }
    
    public void setAcsIdpedidoPrato(int acsIdpedidoPrato) {
        this.acsIdpedidoPrato = acsIdpedidoPrato;
    }

    
    @Column(name="acs_pedido")
    public Integer getAcsPedido() {
        return this.acsPedido;
    }
    
    public void setAcsPedido(Integer acsPedido) {
        this.acsPedido = acsPedido;
    }

    
    @Column(name="acs_prato")
    public Integer getAcsPrato() {
        return this.acsPrato;
    }
    
    public void setAcsPrato(Integer acsPrato) {
        this.acsPrato = acsPrato;
    }

    
    @Column(name="acs_quantidade", nullable=false, length=45)
    public String getAcsQuantidade() {
        return this.acsQuantidade;
    }
    
    public void setAcsQuantidade(String acsQuantidade) {
        this.acsQuantidade = acsQuantidade;
    }

    
    @Column(name="acs_valorUnitario", nullable=false, precision=7)
    public BigDecimal getAcsValorUnitario() {
        return this.acsValorUnitario;
    }
    
    public void setAcsValorUnitario(BigDecimal acsValorUnitario) {
        this.acsValorUnitario = acsValorUnitario;
    }




}


