package bean;
// Generated 18/09/2023 17:08:34 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AcsProduto generated by hbm2java
 */
@Entity
@Table(name="acs_produto"
    ,catalog="db_alan_batista"
)
public class AcsProduto  implements java.io.Serializable {


     private int acsIdproduto;
     private String acsNome;
     private String acsDescricao;
     private double acsPreco;
     private String acsAcompanhamento;
     private String acsIngredientes;
     private int acsTempopreparo;
     private short acsCategoria;
     private double acsAvaliacao;
     private String acsPeso;
     private int acsQuantidadepessoas;

    public AcsProduto() {
    }

    public AcsProduto(int acsIdproduto, String acsNome, String acsDescricao, double acsPreco, String acsAcompanhamento, String acsIngredientes, int acsTempopreparo, short acsCategoria, double acsAvaliacao, String acsPeso, int acsQuantidadepessoas) {
       this.acsIdproduto = acsIdproduto;
       this.acsNome = acsNome;
       this.acsDescricao = acsDescricao;
       this.acsPreco = acsPreco;
       this.acsAcompanhamento = acsAcompanhamento;
       this.acsIngredientes = acsIngredientes;
       this.acsTempopreparo = acsTempopreparo;
       this.acsCategoria = acsCategoria;
       this.acsAvaliacao = acsAvaliacao;
       this.acsPeso = acsPeso;
       this.acsQuantidadepessoas = acsQuantidadepessoas;
    }
   
     @Id 

    
    @Column(name="acs_idproduto", unique=true, nullable=false)
    public int getAcsIdproduto() {
        return this.acsIdproduto;
    }
    
    public void setAcsIdproduto(int acsIdproduto) {
        this.acsIdproduto = acsIdproduto;
    }

    
    @Column(name="acs_nome", nullable=false, length=45)
    public String getAcsNome() {
        return this.acsNome;
    }
    
    public void setAcsNome(String acsNome) {
        this.acsNome = acsNome;
    }

    
    @Column(name="acs_descricao", nullable=false)
    public String getAcsDescricao() {
        return this.acsDescricao;
    }
    
    public void setAcsDescricao(String acsDescricao) {
        this.acsDescricao = acsDescricao;
    }

    
    @Column(name="acs_preco", nullable=false, precision=8)
    public double getAcsPreco() {
        return this.acsPreco;
    }
    
    public void setAcsPreco(double acsPreco) {
        this.acsPreco = acsPreco;
    }

    
    @Column(name="acs_acompanhamento", nullable=false)
    public String getAcsAcompanhamento() {
        return this.acsAcompanhamento;
    }
    
    public void setAcsAcompanhamento(String acsAcompanhamento) {
        this.acsAcompanhamento = acsAcompanhamento;
    }

    
    @Column(name="acs_ingredientes", nullable=false)
    public String getAcsIngredientes() {
        return this.acsIngredientes;
    }
    
    public void setAcsIngredientes(String acsIngredientes) {
        this.acsIngredientes = acsIngredientes;
    }

    
    @Column(name="acs_tempopreparo", nullable=false)
    public int getAcsTempopreparo() {
        return this.acsTempopreparo;
    }
    
    public void setAcsTempopreparo(int acsTempopreparo) {
        this.acsTempopreparo = acsTempopreparo;
    }

    
    @Column(name="acs_categoria", nullable=false)
    public short getAcsCategoria() {
        return this.acsCategoria;
    }
    
    public void setAcsCategoria(short acsCategoria) {
        this.acsCategoria = acsCategoria;
    }

    
    @Column(name="acs_avaliacao", nullable=false, precision=3)
    public double getAcsAvaliacao() {
        return this.acsAvaliacao;
    }
    
    public void setAcsAvaliacao(double acsAvaliacao) {
        this.acsAvaliacao = acsAvaliacao;
    }

    
    @Column(name="acs_peso", nullable=false, length=10)
    public String getAcsPeso() {
        return this.acsPeso;
    }
    
    public void setAcsPeso(String acsPeso) {
        this.acsPeso = acsPeso;
    }

    
    @Column(name="acs_quantidadepessoas", nullable=false)
    public int getAcsQuantidadepessoas() {
        return this.acsQuantidadepessoas;
    }
    
    public void setAcsQuantidadepessoas(int acsQuantidadepessoas) {
        this.acsQuantidadepessoas = acsQuantidadepessoas;
    }




}


