package bean;
// Generated 16/09/2023 13:12:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AcsPrato generated by hbm2java
 */
@Entity
@Table(name="acs_prato"
    ,catalog="db_alan_batista"
)
public class AcsPrato  implements java.io.Serializable {


     private int acsIdprato;
     private String acsNome;
     private String acsDescricao;
     private BigDecimal acsPreco;
     private String acsAcompanhamento;
     private String acsIngredientes;
     private int acsTempopreparo;
     private short acsCategoria;
     private BigDecimal acsAvaliacao;
     private String acsPeso;
     private int acsQuantidadepessoas;

    public AcsPrato() {
    }

    public AcsPrato(int acsIdprato, String acsNome, String acsDescricao, BigDecimal acsPreco, String acsAcompanhamento, String acsIngredientes, int acsTempopreparo, short acsCategoria, BigDecimal acsAvaliacao, String acsPeso, int acsQuantidadepessoas) {
       this.acsIdprato = acsIdprato;
       this.acsNome = acsNome;
       this.acsDescricao = acsDescricao;
       this.acsPreco = acsPreco;
       this.acsAcompanhamento = acsAcompanhamento;
       this.acsIngredientes = acsIngredientes;
       this.acsTempopreparo = acsTempopreparo;
       this.acsCategoria = acsCategoria;
       this.acsAvaliacao = acsAvaliacao;
       this.acsPeso = acsPeso;
       this.acsQuantidadepessoas = acsQuantidadepessoas;
    }
   
     @Id 

    
    @Column(name="acs_idprato", unique=true, nullable=false)
    public int getAcsIdprato() {
        return this.acsIdprato;
    }
    
    public void setAcsIdprato(int acsIdprato) {
        this.acsIdprato = acsIdprato;
    }

    
    @Column(name="acs_nome", nullable=false, length=45)
    public String getAcsNome() {
        return this.acsNome;
    }
    
    public void setAcsNome(String acsNome) {
        this.acsNome = acsNome;
    }

    
    @Column(name="acs_descricao", nullable=false)
    public String getAcsDescricao() {
        return this.acsDescricao;
    }
    
    public void setAcsDescricao(String acsDescricao) {
        this.acsDescricao = acsDescricao;
    }

    
    @Column(name="acs_preco", nullable=false, precision=8)
    public BigDecimal getAcsPreco() {
        return this.acsPreco;
    }
    
    public void setAcsPreco(BigDecimal acsPreco) {
        this.acsPreco = acsPreco;
    }

    
    @Column(name="acs_acompanhamento", nullable=false)
    public String getAcsAcompanhamento() {
        return this.acsAcompanhamento;
    }
    
    public void setAcsAcompanhamento(String acsAcompanhamento) {
        this.acsAcompanhamento = acsAcompanhamento;
    }

    
    @Column(name="acs_ingredientes", nullable=false)
    public String getAcsIngredientes() {
        return this.acsIngredientes;
    }
    
    public void setAcsIngredientes(String acsIngredientes) {
        this.acsIngredientes = acsIngredientes;
    }

    
    @Column(name="acs_tempopreparo", nullable=false)
    public int getAcsTempopreparo() {
        return this.acsTempopreparo;
    }
    
    public void setAcsTempopreparo(int acsTempopreparo) {
        this.acsTempopreparo = acsTempopreparo;
    }

    
    @Column(name="acs_categoria", nullable=false)
    public short getAcsCategoria() {
        return this.acsCategoria;
    }
    
    public void setAcsCategoria(short acsCategoria) {
        this.acsCategoria = acsCategoria;
    }

    
    @Column(name="acs_avaliacao", nullable=false, precision=3)
    public BigDecimal getAcsAvaliacao() {
        return this.acsAvaliacao;
    }
    
    public void setAcsAvaliacao(BigDecimal acsAvaliacao) {
        this.acsAvaliacao = acsAvaliacao;
    }

    
    @Column(name="acs_peso", nullable=false, length=10)
    public String getAcsPeso() {
        return this.acsPeso;
    }
    
    public void setAcsPeso(String acsPeso) {
        this.acsPeso = acsPeso;
    }

    
    @Column(name="acs_quantidadepessoas", nullable=false)
    public int getAcsQuantidadepessoas() {
        return this.acsQuantidadepessoas;
    }
    
    public void setAcsQuantidadepessoas(int acsQuantidadepessoas) {
        this.acsQuantidadepessoas = acsQuantidadepessoas;
    }




}


