package bean;
// Generated 16/09/2023 13:12:01 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcsPedido generated by hbm2java
 */
@Entity
@Table(name="acs_pedido"
    ,catalog="db_alan_batista"
)
public class AcsPedido  implements java.io.Serializable {


     private int acsIdpedido;
     private Integer acsCliente;
     private Date acsHorapedido;
     private String acsValor;
     private int acsFuncionario;

    public AcsPedido() {
    }

	
    public AcsPedido(int acsIdpedido, Date acsHorapedido, String acsValor, int acsFuncionario) {
        this.acsIdpedido = acsIdpedido;
        this.acsHorapedido = acsHorapedido;
        this.acsValor = acsValor;
        this.acsFuncionario = acsFuncionario;
    }
    public AcsPedido(int acsIdpedido, Integer acsCliente, Date acsHorapedido, String acsValor, int acsFuncionario) {
       this.acsIdpedido = acsIdpedido;
       this.acsCliente = acsCliente;
       this.acsHorapedido = acsHorapedido;
       this.acsValor = acsValor;
       this.acsFuncionario = acsFuncionario;
    }
   
     @Id 

    
    @Column(name="acs_idpedido", unique=true, nullable=false)
    public int getAcsIdpedido() {
        return this.acsIdpedido;
    }
    
    public void setAcsIdpedido(int acsIdpedido) {
        this.acsIdpedido = acsIdpedido;
    }

    
    @Column(name="acs_cliente")
    public Integer getAcsCliente() {
        return this.acsCliente;
    }
    
    public void setAcsCliente(Integer acsCliente) {
        this.acsCliente = acsCliente;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="acs_horapedido", nullable=false, length=19)
    public Date getAcsHorapedido() {
        return this.acsHorapedido;
    }
    
    public void setAcsHorapedido(Date acsHorapedido) {
        this.acsHorapedido = acsHorapedido;
    }

    
    @Column(name="acs_valor", nullable=false, length=45)
    public String getAcsValor() {
        return this.acsValor;
    }
    
    public void setAcsValor(String acsValor) {
        this.acsValor = acsValor;
    }

    
    @Column(name="acs_funcionario", nullable=false)
    public int getAcsFuncionario() {
        return this.acsFuncionario;
    }
    
    public void setAcsFuncionario(int acsFuncionario) {
        this.acsFuncionario = acsFuncionario;
    }




}


