package bean;
// Generated 18/09/2023 17:08:34 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AcsUsuario generated by hbm2java
 */
@Entity
@Table(name="acs_usuario"
    ,catalog="db_alan_batista"
)
public class AcsUsuario  implements java.io.Serializable {


     private int acsIdusuario;
     private String acsNome;
     private String acsApelido;
     private String acsCpf;
     private String acsDataNasc;
     private String acsSenha;
     private int acsNivel;
     private String acsAtivo;

    public AcsUsuario() {
    }

    public AcsUsuario(int acsIdusuario, String acsNome, String acsApelido, String acsCpf, String acsDataNasc, String acsSenha, int acsNivel, String acsAtivo) {
       this.acsIdusuario = acsIdusuario;
       this.acsNome = acsNome;
       this.acsApelido = acsApelido;
       this.acsCpf = acsCpf;
       this.acsDataNasc = acsDataNasc;
       this.acsSenha = acsSenha;
       this.acsNivel = acsNivel;
       this.acsAtivo = acsAtivo;
    }
   
     @Id 

    
    @Column(name="acs_idusuario", unique=true, nullable=false)
    public int getAcsIdusuario() {
        return this.acsIdusuario;
    }
    
    public void setAcsIdusuario(int acsIdusuario) {
        this.acsIdusuario = acsIdusuario;
    }

    
    @Column(name="acs_nome", nullable=false, length=70)
    public String getAcsNome() {
        return this.acsNome;
    }
    
    public void setAcsNome(String acsNome) {
        this.acsNome = acsNome;
    }

    
    @Column(name="acs_apelido", nullable=false, length=25)
    public String getAcsApelido() {
        return this.acsApelido;
    }
    
    public void setAcsApelido(String acsApelido) {
        this.acsApelido = acsApelido;
    }

    
    @Column(name="acs_cpf", nullable=false, length=45)
    public String getAcsCpf() {
        return this.acsCpf;
    }
    
    public void setAcsCpf(String acsCpf) {
        this.acsCpf = acsCpf;
    }

    
    @Column(name="acs_dataNasc", nullable=false, length=45)
    public String getAcsDataNasc() {
        return this.acsDataNasc;
    }
    
    public void setAcsDataNasc(String acsDataNasc) {
        this.acsDataNasc = acsDataNasc;
    }

    
    @Column(name="acs_senha", nullable=false, length=45)
    public String getAcsSenha() {
        return this.acsSenha;
    }
    
    public void setAcsSenha(String acsSenha) {
        this.acsSenha = acsSenha;
    }

    
    @Column(name="acs_nivel", nullable=false)
    public int getAcsNivel() {
        return this.acsNivel;
    }
    
    public void setAcsNivel(int acsNivel) {
        this.acsNivel = acsNivel;
    }

    
    @Column(name="acs_ativo", nullable=false, length=1)
    public String getAcsAtivo() {
        return this.acsAtivo;
    }
    
    public void setAcsAtivo(String acsAtivo) {
        this.acsAtivo = acsAtivo;
    }




}


