package bean;
// Generated 08/12/2023 16:14:48 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcsVendas generated by hbm2java
 */
@Entity
@Table(name="acs_vendas"
    ,catalog="db_alan_batista"
)
public class AcsVendas  implements java.io.Serializable {


     private int acsIdvendas;
     private AcsCliente acsCliente;
     private AcsFuncionario acsFuncionario;
     private Date acsHorapedido;
     private double acsValor;

    public AcsVendas() {
    }

	
    public AcsVendas(int acsIdvendas, AcsFuncionario acsFuncionario, Date acsHorapedido, double acsValor) {
        this.acsIdvendas = acsIdvendas;
        this.acsFuncionario = acsFuncionario;
        this.acsHorapedido = acsHorapedido;
        this.acsValor = acsValor;
    }
    public AcsVendas(int acsIdvendas, AcsCliente acsCliente, AcsFuncionario acsFuncionario, Date acsHorapedido, double acsValor, Set acsVendasProdutos) {
       this.acsIdvendas = acsIdvendas;
       this.acsCliente = acsCliente;
       this.acsFuncionario = acsFuncionario;
       this.acsHorapedido = acsHorapedido;
       this.acsValor = acsValor;
    }
   
     @Id 

    
    @Column(name="acs_idvendas", unique=true, nullable=false)
    public int getAcsIdvendas() {
        return this.acsIdvendas;
    }
    
    public void setAcsIdvendas(int acsIdvendas) {
        this.acsIdvendas = acsIdvendas;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="acs_cliente")
    public AcsCliente getAcsCliente() {
        return this.acsCliente;
    }
    
    public void setAcsCliente(AcsCliente acsCliente) {
        this.acsCliente = acsCliente;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="acs_funcionario", nullable=false)
    public AcsFuncionario getAcsFuncionario() {
        return this.acsFuncionario;
    }
    
    public void setAcsFuncionario(AcsFuncionario acsFuncionario) {
        this.acsFuncionario = acsFuncionario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="acs_horapedido", nullable=false, length=19)
    public Date getAcsHorapedido() {
        return this.acsHorapedido;
    }
    
    public void setAcsHorapedido(Date acsHorapedido) {
        this.acsHorapedido = acsHorapedido;
    }

    
    @Column(name="acs_valor", nullable=false)
    public double getAcsValor() {
        return this.acsValor;
    }
    
    public void setAcsValor(double acsValor) {
        this.acsValor = acsValor;
    }


}


