package bean;
// Generated 18/09/2023 17:08:34 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AcsVendasProduto generated by hbm2java
 */
@Entity
@Table(name="acs_vendas_produto"
    ,catalog="db_alan_batista"
)
public class AcsVendasProduto  implements java.io.Serializable {


     private int acsIdvendasProduto;
     private int acsVendas;
     private int acsProduto;
     private String acsQuantidade;
     private double acsValorUnitario;

    public AcsVendasProduto() {
    }

    public AcsVendasProduto(int acsIdvendasProduto, int acsVendas, int acsProduto, String acsQuantidade, double acsValorUnitario) {
       this.acsIdvendasProduto = acsIdvendasProduto;
       this.acsVendas = acsVendas;
       this.acsProduto = acsProduto;
       this.acsQuantidade = acsQuantidade;
       this.acsValorUnitario = acsValorUnitario;
    }
   
     @Id 

    
    @Column(name="acs_idvendas_produto", unique=true, nullable=false)
    public int getAcsIdvendasProduto() {
        return this.acsIdvendasProduto;
    }
    
    public void setAcsIdvendasProduto(int acsIdvendasProduto) {
        this.acsIdvendasProduto = acsIdvendasProduto;
    }

    
    @Column(name="acs_vendas", nullable=false)
    public int getAcsVendas() {
        return this.acsVendas;
    }
    
    public void setAcsVendas(int acsVendas) {
        this.acsVendas = acsVendas;
    }

    
    @Column(name="acs_produto", nullable=false)
    public int getAcsProduto() {
        return this.acsProduto;
    }
    
    public void setAcsProduto(int acsProduto) {
        this.acsProduto = acsProduto;
    }

    
    @Column(name="acs_quantidade", nullable=false, length=45)
    public String getAcsQuantidade() {
        return this.acsQuantidade;
    }
    
    public void setAcsQuantidade(String acsQuantidade) {
        this.acsQuantidade = acsQuantidade;
    }

    
    @Column(name="acs_valorUnitario", nullable=false, precision=7)
    public double getAcsValorUnitario() {
        return this.acsValorUnitario;
    }
    
    public void setAcsValorUnitario(double acsValorUnitario) {
        this.acsValorUnitario = acsValorUnitario;
    }




}


