package bean;
// Generated 18/09/2023 17:08:34 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcsVendas generated by hbm2java
 */
@Entity
@Table(name="acs_vendas"
    ,catalog="db_alan_batista"
)
public class AcsVendas  implements java.io.Serializable {


     private int acsIdvendas;
     private int acsCliente;
     private Date acsHorapedido;
     private String acsValor;
     private int acsFuncionario;

    public AcsVendas() {
    }

	
    public AcsVendas(int acsIdvendas, Date acsHorapedido, String acsValor, int acsFuncionario) {
        this.acsIdvendas = acsIdvendas;
        this.acsHorapedido = acsHorapedido;
        this.acsValor = acsValor;
        this.acsFuncionario = acsFuncionario;
    }
    public AcsVendas(int acsIdvendas, int acsCliente, Date acsHorapedido, String acsValor, int acsFuncionario) {
       this.acsIdvendas = acsIdvendas;
       this.acsCliente = acsCliente;
       this.acsHorapedido = acsHorapedido;
       this.acsValor = acsValor;
       this.acsFuncionario = acsFuncionario;
    }
   
     @Id 

    
    @Column(name="acs_idvendas", unique=true, nullable=false)
    public int getAcsIdvendas() {
        return this.acsIdvendas;
    }
    
    public void setAcsIdvendas(int acsIdvendas) {
        this.acsIdvendas = acsIdvendas;
    }

    
    @Column(name="acs_cliente")
    public int getAcsCliente() {
        return this.acsCliente;
    }
    
    public void setAcsCliente(int acsCliente) {
        this.acsCliente = acsCliente;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="acs_horapedido", nullable=false, length=19)
    public Date getAcsHorapedido() {
        return this.acsHorapedido;
    }
    
    public void setAcsHorapedido(Date acsHorapedido) {
        this.acsHorapedido = acsHorapedido;
    }

    
    @Column(name="acs_valor", nullable=false, length=45)
    public String getAcsValor() {
        return this.acsValor;
    }
    
    public void setAcsValor(String acsValor) {
        this.acsValor = acsValor;
    }

    
    @Column(name="acs_funcionario", nullable=false)
    public int getAcsFuncionario() {
        return this.acsFuncionario;
    }
    
    public void setAcsFuncionario(int acsFuncionario) {
        this.acsFuncionario = acsFuncionario;
    }




}


