package bean;
// Generated 08/12/2023 16:14:48 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcsVendasProduto generated by hbm2java
 */
@Entity
@Table(name="acs_vendas_produto"
    ,catalog="db_alan_batista"
)
public class AcsVendasProduto  implements java.io.Serializable {


     private int acsIdvendasProduto;
     private AcsProduto acsProduto;
     private AcsVendas acsVendas;
     private String acsQuantidade;
     private double acsValorUnitario;

    public AcsVendasProduto() {
    }

    public AcsVendasProduto(int acsIdvendasProduto, AcsProduto acsProduto, AcsVendas acsVendas, String acsQuantidade, double acsValorUnitario) {
       this.acsIdvendasProduto = acsIdvendasProduto;
       this.acsProduto = acsProduto;
       this.acsVendas = acsVendas;
       this.acsQuantidade = acsQuantidade;
       this.acsValorUnitario = acsValorUnitario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="acs_idvendas_produto", unique=true, nullable=false)
    public int getAcsIdvendasProduto() {
        return this.acsIdvendasProduto;
    }
    
    public void setAcsIdvendasProduto(int acsIdvendasProduto) {
        this.acsIdvendasProduto = acsIdvendasProduto;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="acs_produto", nullable=false)
    public AcsProduto getAcsProduto() {
        return this.acsProduto;
    }
    
    public void setAcsProduto(AcsProduto acsProduto) {
        this.acsProduto = acsProduto;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="acs_vendas", nullable=false)
    public AcsVendas getAcsVendas() {
        return this.acsVendas;
    }
    
    public void setAcsVendas(AcsVendas acsVendas) {
        this.acsVendas = acsVendas;
    }

    
    @Column(name="acs_quantidade", nullable=false, length=45)
    public String getAcsQuantidade() {
        return this.acsQuantidade;
    }
    
    public void setAcsQuantidade(String acsQuantidade) {
        this.acsQuantidade = acsQuantidade;
    }

    
    @Column(name="acs_valorUnitario", nullable=false, precision=7)
    public double getAcsValorUnitario() {
        return this.acsValorUnitario;
    }
    
    public void setAcsValorUnitario(double acsValorUnitario) {
        this.acsValorUnitario = acsValorUnitario;
    }




}


